query GetPublicYuAPIConfig {
  config: getPublicYuAPIConfig {
    language
    stripeKey
    mixpanelKey
    enabledCaptchaProviders
    hcaptchaSiteKey
    urls {
      members
      website
      privacyPolicy
      rewardsPolicy
    }
    intercom {
      appId
      ios
      android
    }
    leanplum {
      appId
      prodKey
      devKey
    }
    sduiStaticDeeplinks {
      name
      stepId
      dynamicRouteId
    }
    sduiJourney {
      supportRequest
    }
    sessionTimeout
  }
}
