import { CoverType } from "@graphql/_core/schema/globalTypes";

export const DATA = {
  right: {
    slot1: {
      __typename: "YuProduct",
      code: "YULGL",
      coverType: CoverType.rare,
      description:
        "We’re working hard to bring you the best insurance products on the market. Vote for what you want to see here.",
      earnRate: 0,
      itemSlot: "chest",
      name: "Group Life Insurance",
      productId: "group_life_insurance",
      productType: "employer",
      status: "unlockable",
      policyNumber: 0,
      picture: require("./chest/Chest-clean.png"),
    },
    slot2: {
      __typename: "YuProduct",
      code: "YUGLIP",
      coverType: CoverType.rare,
      description:
        "We’re working hard to bring you the best insurance products on the market. Vote for what you want to see here.",
      earnRate: 20,
      itemSlot: "place_holder",
      name: "",
      productId: "group_income_protection",
      productType: "employer",
      status: "locked",
      policyNumber: 0,
      picture: require("./placeholder/Placeholder.png"),
    },
    slot3: {
      __typename: "YuProduct",
      code: "YULGLCI",
      coverType: CoverType.rare,
      description:
        "We’re working hard to bring you the best insurance products on the market. Vote for what you want to see here.",
      earnRate: 20,
      itemSlot: "place_holder",
      name: "",
      productId: "group_critical_illness",
      productType: "employer",
      status: "locked",
      policyNumber: 0,
      picture: require("./placeholder/Placeholder.png"),
    },
    slot4: {
      __typename: "YuProduct",
      code: "YUALPH",
      coverType: CoverType.rare,
      description:
        "We’re working hard to bring you the best insurance products on the market. Vote for what you want to see here.",
      earnRate: 20,
      itemSlot: "place_holder",
      name: "Pocket Watch",
      productId: "yulife_alpha",
      productType: "alpha",
      status: "locked",
      policyNumber: 0,
      picture: require("./placeholder/Placeholder.png"),
    },
  },
  left: {
    slot1: {
      __typename: "YuProduct",
      code: "YULFIB",
      coverType: CoverType.epic,
      description: "Protect your family financially with a proportion of your monthly income should the worst happen.",
      earnRate: 30,
      itemSlot: "chest",
      name: "Chest of Life Insurance",
      options: [Array],
      productId: "family_income_benefit",
      productType: "personal",
      status: "active",
      policyNumber: 0,
      picture: require("./chest/chest.png"),
    },
    slot2: {
      __typename: "YuProduct",
      code: "YULIP",
      coverType: CoverType.rare,
      description: "Vote for what you would like to see here.",
      earnRate: 10,
      itemSlot: "chest",
      name: "Income Protection",
      options: [Array],
      productId: "income_protection",
      productType: "personal",
      status: "active",
      policyNumber: 0,
      picture: require("./chest/chest.png"),
    },
    slot3: {
      __typename: "YuProduct",
      code: "YULCI",
      coverType: CoverType.common,
      description: "Vote for what you would like to see here.",
      earnRate: 5,
      itemSlot: "pants",
      name: "Critical Illness",
      options: [Array],
      productId: "critical_illness",
      productType: "personal",
      status: "active",
      policyNumber: 0,
      picture: require("./chest/chest.png"),
    },
    slot4: {
      __typename: "YuProduct",
      code: "YULT",
      coverType: CoverType.rare,
      description: "Vote for what you would like to see here.",
      earnRate: 10,
      itemSlot: "boots",
      name: "Travel Insurance",
      options: [Array],
      productId: "travel",
      productType: "personal",
      status: "locked",
      policyNumber: 0,
      picture: require("./chest/Chest-clean.png"),
    },
  },
  bottom: {
    slot1: {
      __typename: "YuProduct",
      code: "YULFIB",
      coverType: CoverType.epic,
      description: "Protect your family financially with a proportion of your monthly income should the worst happen.",
      earnRate: 30,
      itemSlot: "chest",
      name: "Chest of Life Insurance",
      options: [Array],
      productId: "family_income_benefit",
      productType: "personal",
      status: "active",
      policyNumber: 0,
      picture: require("./chest/chest.png"),
    },
    slot2: {
      __typename: "YuProduct",
      code: "YULIP",
      coverType: CoverType.rare,
      description: "Vote for what you would like to see here.",
      earnRate: 10,
      itemSlot: "chest",
      name: "Income Protection",
      options: [Array],
      productId: "income_protection",
      productType: "personal",
      status: "active",
      policyNumber: 0,
      picture: require("./chest/chest.png"),
    },
    slot3: {
      __typename: "YuProduct",
      code: "YULCI",
      coverType: CoverType.common,
      description: "Vote for what you would like to see here.",
      earnRate: 5,
      itemSlot: "pants",
      name: "Critical Illness",
      options: [Array],
      productId: "critical_illness",
      productType: "personal",
      status: "active",
      policyNumber: 0,
      picture: require("./chest/chest.png"),
    },
    slot4: {
      __typename: "YuProduct",
      code: "YULT",
      coverType: CoverType.rare,
      description: "Vote for what you would like to see here.",
      earnRate: 10,
      itemSlot: "boots",
      name: "Travel Insurance",
      options: [Array],
      productId: "travel",
      productType: "personal",
      status: "locked",
      policyNumber: 0,
      picture: require("./chest/Chest-clean.png"),
    },
  },

  getYulifer: {
    __typename: "Yulifer",
    avatarRemoteFiles: {
      __typename: "AvatarRemoteFiles",
      pngFull:
        "http://res.cloudinary.com/yu-life-develop/image/upload/s--VWzgzHgU--/c_fit,h_1106,q_auto,w_530/v1/api/local/avatars/1DEAC64B88DE476F87192D628F9F4F77.png",
      pngMini:
        "http://res.cloudinary.com/yu-life-develop/image/upload/s--VWzgzHgU--/c_fit,h_1106,q_auto,w_530/v1/api/local/avatars/1DEAC64B88DE476F87192D628F9F4F77.png",
      svgFull:
        "http://res.cloudinary.com/yu-life-develop/image/upload/s--VWzgzHgU--/c_fit,h_1106,q_auto,w_530/v1/api/local/avatars/1DEAC64B88DE476F87192D628F9F4F77.png",
    },
    earnRate: 10,
    isAvatarCreated: true,
    userId: "1DEAC64B88DE476F87192D628F9F4F77",
  },
} as any;
