import { IDatabaseItem, generateRandomMongoId } from "@yu-life/yulife-bdd-framework";
import moment from "moment";

export const AUTH_TEMPLATE = {
  type: "mongo",
  modelName: "authpassword",
  data: {
    userId: generateRandomMongoId(),
    attempts: 1,
    lastAttempt: moment().subtract(1, "day").format(),
    lastIp: "35.176.60.174",
    password: "letmein",
    scope: "user",
    strategy: "0",
    used: false,
  },
} as IDatabaseItem;

export const DEFAULT_TOGGLES = {
  type: "mongo",
  modelName: "usertoggles",
  data: {
    _id: generateRandomMongoId(),
    userId: generateRandomMongoId(),
    features: {
      showNotifications: true,
      showStreaks: true,
      showCounter: true,
      showBuildNumber: true,
      showSettings: true,
      disableUserEntries: true,
      fitbit: true,
      showConnections: true,
      showLastSynced: true,
      newPassiveValidationRule: true,
      usePassiveMeditation: true,
      statsShowCoinGeneralTotalYearned: true,
      statsShowCoinRecommendationCard: true,
      statsShowCoinGeneralTotalRedeemedCard: true,
      statsShowCoinAchievementCard: true,
      statsShowChallengeGeneralCard: true,
      statsShowChallengeRecommendationCard: true,
      statsShowChallengeComparisonCard: true,
      statsShowStepsRecommendationCard: true,
      statsShowStepsGeneralCard: true,
      statsShowStepsBestScoreCard: true,
      statsShowStepsGraphCard: true,
      statsShowMindfulnessRecommendationCard: true,
      statsShowMindfulnessGeneralCard: true,
      statsShowMindfulnessBestScoreCard: true,
      statsShowMindfulnessGraphCard: true,
      statsShowCyclingRecommendationCard: true,
      statsShowCyclingGeneralCard: true,
      statsShowCyclingBestScoreCard: true,
      statsShowCyclingGraphCard: true,
      showStats: true,
      hideSmartHealthScreen: true,
      hideYuMatterScreen: false,
      newGamePlus: true,
      unitySurge: true,
      rewardRedemptionDisabled: false,
      showNotificationCentre: true,
      newMediaPlayer: true,
      showYucoinPowerButton: true,
      showBrainGameSudoku: true,
      showFiit: true,
      useNewLeaderboardServices: true,
      enableChallengeBonuses: true,
      showYumojiHeadwear: true,
      newChallengeList: true,
      tempGameGoalWeekliesRefactor: true,
    },
  },
} as IDatabaseItem;
