export type AppDebugMixpanelEvent = {
  location: "fitkit" | "redux";
  type: string;
  reduxEvent?: string;
  payload?: any;
  timestamp?: string;
};

export type MixpanelEventMetadata = AppDebugMixpanelEvent | Record<string, any>;

export type MixpanelEvent =
  | "accordion_interaction"
  | "active_boosts_viewed"
  | "yu_health_debug"
  | "armour_inspected"
  | "avatar_save"
  | "button_pressed"
  | "customer_cover_viewed"
  | "debug_tool_query_args"
  | "debug_tool_query_results"
  | "document_viewed"
  | "wrapped_share_pressed"
  | "end_challenge_result"
  | "end_challenge_triggered"
  | "faq_viewed"
  | "goal_join_error"
  | "information_viewed"
  | "initial_pedometer_steps_set"
  | "invalid_pedometer_steps"
  | "modal_close"
  | "modal_dismissed"
  | "modal_movement"
  | "modal_viewed"
  | "package_inspected"
  | "permission_requested"
  | "question_interaction"
  | "referral_link_copied"
  | "referral_link_shared"
  | "referrals_viewed"
  | "rewards_details_button_pressed"
  | "rewards_details_button_pressed_error"
  | "reward_viewed"
  | "screen_view"
  | "settings_toggle"
  | "survey_completed"
  | "transition_screen_view"
  | "user_action"
  | "user_connection_state"
  | "wellbeing_item_button_pressed"
  | "wellbeing_item_button_pressed_error"
  | "reward_info_viewed"
  | "event_faq_viewed"
  | "media_challenge_end"
  | "media_challenge_missing"
  | "media_challenge_anti_cheat"
  | "media_challenge_resume"
  | "video_player_button_start_pressed"
  | "video_player_play_button_start_pressed"
  | "video_player_start"
  | "video_player_is_playing"
  | "video_player_is_paused"
  | "video_player_focused"
  | "video_player_is_buffering"
  | "casting_seek_attempt_detected"
  | "video_started"
  | "video_cancelled"
  | "video_completed"
  | "item_button_pressed"
  | "item_viewed"
  | "challenge_collection_viewed"
  | "challenge_subcollection_viewed"
  | "media_not_loaded"
  | "mindfulness_app_open"
  | "challenge_selected"
  | "leaderboard_switched"
  | "leaderboard_toggle"
  | "end_challenge_no_data"
  | "audio_player_button_start_pressed"
  | "audio_player_play_button_start_pressed"
  | "audio_player_start"
  | "audio_player_is_playing"
  | "audio_player_is_paused"
  | "audio_player_focused"
  | "audio_player_is_buffering"
  | "audio_started"
  | "audio_cancelled"
  | "audio_completed"
  | "smoking_entry_point"
  | "smoking_sponsorship_viewed"
  | "battlepass_reward_viewed"
  | "battlepass_donation_pressed"
  | "battlepass_level_up"
  | "smoking_streak_carousel_item_viewed"
  | "yuhealth_available_providers_fetched"
  | "yuhealth_permissions_fetched"
  | "wrapped_screen_view"
  | "challenge_progress_debug_tools"
  | "achievement_view"
  | "achievement_click"
  | "breathing_exercise_started"
  | "breathing_exercise_completed"
  | "breathing_exercise_paused"
  | "breathing_exercise_resumed"
  | "breathing_exercise_closed"
  | "team_event_visited";

export enum UserSupportLevel {
  Basic = "basic",
  Enhanced = "enhanced",
  None = "none",
}
