export type AppDebugMixpanelEvent = {
  location: "fitkit" | "redux";
  type: string;
  reduxEvent?: string;
  payload?: any;
  timestamp?: string;
};

export type MixpanelEventMetadata = AppDebugMixpanelEvent | Record<string, any>;

export type MixpanelEvent =
  | "accordion_interaction"
  | "active_boosts_viewed"
  | "app_debug"
  | "armour_inspected"
  | "avatar_save"
  | "button_pressed"
  | "customer_cover_viewed"
  | "debug_tool_query_args"
  | "debug_tool_query_results"
  | "document_viewed"
  | "end_challenge_result"
  | "end_challenge_triggered"
  | "faq_viewed"
  | "goal_join_error"
  | "information_viewed"
  | "initial_pedometer_steps_set"
  | "invalid_pedometer_steps"
  | "modal_close"
  | "modal_dismissed"
  | "modal_movement"
  | "modal_viewed"
  | "package_inspected"
  | "permission_requested"
  | "question_interaction"
  | "referral_link_copied"
  | "referral_link_shared"
  | "referrals_viewed"
  | "rewards_details_button_pressed"
  | "rewards_details_button_pressed_error"
  | "reward_viewed"
  | "screen_view"
  | "settings_toggle"
  | "survey_completed"
  | "transition_screen_view"
  | "user_action"
  | "user_connection_state"
  | "wellbeing_item_button_pressed"
  | "wellbeing_item_button_pressed_error"
  | "reward_info_viewed"
  | "event_faq_viewed"
  | "meditopia_challenge_end"
  | "meditopia_challenge_resume"
  | "video_player_button_start_pressed"
  | "video_player_play_button_start_pressed"
  | "video_player_start"
  | "video_player_is_playing"
  | "video_player_is_paused"
  | "video_player_focused"
  | "video_player_is_buffering"
  | "video_started"
  | "video_cancelled"
  | "video_completed"
  | "item_button_pressed"
  | "item_viewed"
  | "challenge_collection_viewed"
  | "challenge_subcollection_viewed"
  | "media_not_loaded"
  | "mindfulness_app_open"
  | "challenge_selected"
  | "leaderboard_switched"
  | "leaderboard_toggle"
  | "end_challenge_no_data";
