version: 2
registries:
  npm-gitlab:
    type: npm-registry
    url: gitlab.com/api/v4/packages/npm
    token: ${{GITLAB_TOKEN}}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    # Note: We won't use the schedule feature, as we will use the GitLab CI/CD pipeline to trigger the Dependabot job
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    open-security-pull-requests-limit: 10
