spec:
  inputs:
    detox_test_type:
      type: string
      default: "healthcheck"
      description: "Detox test type to run"
      options:
        - activity
        - activity:2
        - admin
        - admin:2
        - battle-pass
        - benefits
        - cash_plan
        - challenges
        - challenges-2
        - challenges-extended
        - healthcheck
        - jp
        - overnight
        - personal
        - reward-passes
        - sa
        - screenshots
        - smoke
        - smoking
        - surveys
        - usa
        - worlds
        - worlds-2
        - yuscreen
    api_branch_name:
      type: string
      default: "develop"
      description: "Target API container branch"
---
include:
  - local: "gitlab/.build.yml"
  - local: "gitlab/.cache.yml"
  - local: "gitlab/.quality.yml"
  - local: "gitlab/.release.yml"
  - local: "gitlab/.storybook.yml"
  - local: "gitlab/.test.yml"
  - local: "gitlab/.translate.yml"
  - local: "gitlab/.version-label.yml"
  - local: "gitlab/.debug-build.yml"
  - local: "gitlab/.build-android.yml"
  - local: "gitlab/.build-ios.yml"
  - local: "gitlab/.e2e.yml"
    inputs:
      detox_test_type: $[[ inputs.detox_test_type ]]
      api_branch_name: $[[ inputs.api_branch_name ]]
  - project: "yu-life/infrastructure/yulife-devops-shared-config"
    ref: main
    file:
      - "shared-gitlab-config/generic-node.yml"
  - component: $CI_SERVER_FQDN/yu-life/infrastructure/yulife-devops-shared-config/global-default@global-default-1
  - component: $CI_SERVER_FQDN/yu-life/infrastructure/yulife-devops-shared-config/assume-aws-role-with-web-identity@assume-aws-role-with-web-identity-2
    inputs:
      job_name: assume-aws-role-with-web-identity:uk-dev:app-components
      role_arn: $UK_DEV_APP_COMPONENTS_ROLE_ARN
  - component: $CI_SERVER_FQDN/yu-life/infrastructure/yulife-devops-shared-config/assume-aws-role-with-web-identity@assume-aws-role-with-web-identity-2
    inputs:
      job_name: assume-aws-role-with-web-identity:devops:develop-builds
      role_arn: $DEVELOP_BUILDS_ROLE_ARN
  - component: $CI_SERVER_FQDN/yu-life/infrastructure/yulife-devops-shared-config/assume-aws-role-with-web-identity@assume-aws-role-with-web-identity-2.0.0
    inputs:
      job_name: assume-aws-role-with-web-identity:devops:production-builds
      role_arn: $PRODUCTION_BUILDS_ROLE_ARN

variables:
  UK_DEV_AWS_ACCOUNT_ID: 846880112034
  TEAM_QA_AWS_ACCOUNT_ID: 209479303709
  DEVOPS_AWS_ACCOUNT_ID: 112259133553
  UK_DEV_APP_COMPONENTS_ROLE_ARN: arn:aws:iam::$UK_DEV_AWS_ACCOUNT_ID:role/oidc/OIDC-gitlab-yulife-app-components
  GITLAB_TOKEN: $CI_JOB_TOKEN
  QA_REPORTER_ROLE_ARN: arn:aws:iam::$TEAM_QA_AWS_ACCOUNT_ID:role/oidc/OIDC-gitlab-yulife-cypress-reports
  # MacOS VM v1.3.0: MacOS 26.2 tahoe with Xcode versions 26.2 and 16.4 - PG 18
  # https://gitlab.com/yu-life/infrastructure/yulife-devops-packer/-/blob/main/packer/macos-xcode/CHANGELOG.md#130---2026-02-23
  MACOS_VM_IMAGE_VERSION: v1.3.0
  MACOS_VM_IMAGE: $DEVOPS_AWS_ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/yulife-macos-xcode:$MACOS_VM_IMAGE_VERSION
  IOS_XCODE_VERSION: 26.2
  DEVELOPER_DIR: "/Applications/Xcode_${IOS_XCODE_VERSION}.app"
  DEVELOP_BUILDS_ROLE_ARN: arn:aws:iam::$DEVOPS_AWS_ACCOUNT_ID:role/oidc/OIDC-gitlab-develop-react-native-builds
  PRODUCTION_BUILDS_ROLE_ARN: arn:aws:iam::$DEVOPS_AWS_ACCOUNT_ID:role/oidc/OIDC-gitlab-production-react-native-builds
  BINARY_S3_BUCKET_NAME: yu-shared-react-native-binaries
  LAMBDA_DOWNLOADS_URL: https://builds.yulife.dev/download
  FL_ANDROID_DEVELOP_KEYSTORE_PATH: .secure_files/yulife-android-develop.keystore
  FL_ANDROID_DEVELOP_KEY_ALIAS: yulife-android-develop
  FL_ANDROID_PRODUCTION_KEYSTORE_PATH: .secure_files/yulife-react-native-client.jks
  FL_ANDROID_PRODUCTION_KEY_ALIAS: yulife
  FL_ITC_TEAM_ID: 118777487
  FL_TEAM_ID: 739BJV2T6V
  PNPM_HOME: "$CI_PROJECT_DIR/.pnpm"
  COREPACK_HOME: "$CI_PROJECT_DIR/.cache/node/corepack"

stages:
  - quality
  - build
  - test
  - test-report
  - release
  - translate

.base-macos-vm:
  tags:
    - oakhost_macos_m4
  image: $MACOS_VM_IMAGE
  variables:
    TART_EXECUTOR_SHELL: bash -l
