# Check out https://docs.codemagic.io/yaml/building-a-react-native-app/ for more information
# Cheat sheet: https://docs.codemagic.io/codemagic-yaml-cheatsheet.html
# https://blog.codemagic.io/codemagic-yaml-cheatsheet/
definitions:
  scripts:
    - &install_rn_app_node_dependencies
      name: Install dependencies
      script: |
        corepack enable
        yarn install --frozen-lockfile
    - &build_tsc
      name: Build TSC
      script: |
        yarn tsc
    - &replace_package_version_codes
      name: Replace package version codes
      script: |
        node ./scripts/replace-package-versionCodes.js "$PROJECT_BUILD_NUMBER"
    - &generate_native_projects
      name: Generate native projects
      script: |
        EXPO_NO_GIT_STATUS=1 EXPO_NO_DOTENV=1 npx expo prebuild --platform "$PLATFORM" --clean --no-install
    - &install_cocoapods_dependencies
      name: Install CocoaPods dependencies
      script: |
        cd ios
        bundle config frozen true
        bundle install
        bundle exec pod install --repo-update --deployment
    - &set_ios_provisioning_profiles
      name: Set up provisioning profiles settings on Xcode project
      script: |
        xcode-project use-profiles --project ios/*.xcodeproj
  slack_notify_engineering: &slack_notify_engineering
    slack:
      channel: "#alerts-engineering"
      # TODO: Check with the team if we want to receive builds notifications
      notify_on_build_start: false # To receive a notification when a build starts
      notify:
        success: true
        failure: false # To not receive a notification when a build fails
  develop_branch_trigger: &develop_branch_trigger
    events:
      - push
    branch_patterns:
      - pattern: "develop"
        include: false # TODO: Enable once we migrate to codemagic
        source: false # TODO: Enable once we migrate to codemagic
    cancel_previous_builds: false # Set to `true` to automatically cancel outdated webhook builds

workflows:
  react-native-android-develop:
    name: React Native Android (develop)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      node: v18.20.7
      android_signing:
        - yulife-react-native-android
      groups:
        # List of env vars available on yulife-rn-client group
        # GITLAB_TOKEN: necessary to run yarn install
        - yulife-rn-client
      vars:
        BITRISE_BUILD_NUMBER: $PROJECT_BUILD_NUMBER # TODO: Swap environment variable name once migrated to codemagic
        BUNDLE_ID: "com.yulife.release" # TODO: Override for UAT/Production
        DISPLAY_NAME: "YuLife (develop)" # TODO: Override for UAT/Production
        ENVFILE: ".env.develop" # TODO: Override for UAT/Production
        PLATFORM: android
    scripts:
      - *install_rn_app_node_dependencies
      - *build_tsc
      - *replace_package_version_codes
      - *generate_native_projects
      - name: Set Android SDK location and Java memory
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          echo "org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m" >> "$CM_BUILD_DIR/android/gradle.properties"
      - name: Build Android release
        script: |
          cd android
          ./gradlew assembleRelease --project-prop splitApks=true
      - name: Upload Android sourcemaps to Bugsnag
        script: |
          APP_VERSION=$(cat package.json | jq -r '.version')
          BUGSNAG_API_KEY=$(grep '^BUGSNAG_API_KEY=' .env | cut -d '=' -f2- | tr -d '"')
          npx bugsnag-source-maps upload-react-native \
            --api-key "$BUGSNAG_API_KEY" \
            --platform android \
            --source-map android/app/build/generated/sourcemaps/react/release/index.android.bundle.map \
            --bundle android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle \
            --app-version "$APP_VERSION"
            --app-version-code "$PROJECT_BUILD_NUMBER"
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      <<: *slack_notify_engineering
    triggering:
      <<: *develop_branch_trigger

  react-native-ios-develop:
    name: React Native iOS (develop)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      node: v18.20.7
      ruby: 3.2.2
      xcode: 16.2
      ios_signing:
        bundle_identifier: com.yulife.develop
        distribution_type: ad_hoc
        certificates:
          - yulife-react-native-ios
      groups:
        # List of env vars available on yulife-rn-client group
        # GITLAB_TOKEN: necessary to run yarn install
        - yulife-rn-client
      vars:
        BITRISE_BUILD_NUMBER: $PROJECT_BUILD_NUMBER # TODO: Swap environment variable name once migrated to codemagic
        BUNDLE_ID: "com.yulife.develop" # TODO: Override for UAT/Production
        DISPLAY_NAME: "YuLife (develop)" # TODO: Override for UAT/Production
        ENVFILE: ".env.develop" # TODO: Override for UAT/Production
        PLATFORM: ios
        XCODE_SCHEME: "YuLife"
        XCODE_WORKSPACE: "YuLife.xcworkspace"
        ENABLE_YUWATCH: 1
    scripts:
      - *install_rn_app_node_dependencies
      - *build_tsc
      - *replace_package_version_codes
      - *generate_native_projects
      - *install_cocoapods_dependencies
      - name: Set watch display name
        script: |
          ./scripts/set-watch-display-name.sh "$DISPLAY_NAME"
      - name: Log info.plist
        script: |
          cat ios/YuLife/Info.plist
      - *set_ios_provisioning_profiles
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      <<: *slack_notify_engineering
    triggering:
      <<: *develop_branch_trigger

  ios-detox-base-test: &ios_detox_base_test
    name: iOS Detox Base Test
    max_build_duration: 120
    instance_type: mac_mini_m2
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $HOME/Library/Detox/ios/*
    environment: &ios_detox_base_environment
      node: v18.20.7
      ruby: 3.2.2
      xcode: 16.2
      ios_signing:
        bundle_identifier: com.yulife.develop
        distribution_type: ad_hoc
        certificates:
          - yulife-react-native-ios
      groups:
        # List of env vars available on yulife-rn-client group
        # GITLAB_TOKEN: necessary to run yarn install
        - yulife-rn-client
        # List of env vars available on detox-env-vars group
        # API_BRANCH_NAME: Sets the branch to checkout on the API repo (default: develop)
        # IPHONE_DEVICE: Sets the device to use on the detox test (default: iPhone 16 Pro)
        # DETOX_LOG_LEVEL: Sets the log level to use on the detox test (warn by default)
        # QA_ALERTS_SLACK_WEBHOOK_URL: Sets the webhook URL to use for the qa-alerts Slack channel
        # ALERTS_E2E_SLACK_WEBHOOK_URL: Sets the webhook URL to use for the alerts-e2e-results Slack channel
        - detox-env-vars
      vars: &ios_detox_base_env_vars
        BUNDLE_ID: "com.yulife.develop"
        XCODE_WORKSPACE: "YuLife.xcworkspace"
        XCODE_SCHEME: "YuLife"
        DISPLAY_NAME: "YuLife (e2e)"
        ENVFILE: ".env.e2e"
        BITRISE_BUILD_NUMBER: $PROJECT_BUILD_NUMBER # TODO: Swap environment variable name once migrated to codemagic
        APPLE_TEAM_ID: "739BJV2T6V" # Not set on .env.e2e file, why?
        PLATFORM: ios
        ENABLE_YUWATCH: 0
        REPORT_S3_BUCKET_NAME: yu-eu-west-2-develop-detox-static-origin
        REPORT_DNS_NAME: detox.develop.uk.yulife.engineering
        # Detox env vars to be replaced in each workflow:
        # API_REGION: Sets the region to use on the API repo (default: UK)
        # DETOX_TEST_TYPE: Sets the type of detox test to run (needs to change between workflows)
        # TARGET_LOCALE: Sets the locale to use on the detox test (default: en-GB)
        API_REGION: UK
        TARGET_LOCALE: en-GB
        IPHONE_DEVICE: iPhone 16 Pro
        BITRISE_IO: 1 # TODO: Remove once we migrate to codemagic (for changing API database region) - check pull_run_api_server.sh script
    scripts:
      - *install_rn_app_node_dependencies
      - *build_tsc
      - *replace_package_version_codes
      - *generate_native_projects
      - *install_cocoapods_dependencies
      - *set_ios_provisioning_profiles
      - name: Build app for detox
        script: |
          ./scripts/codemagic/detox_build.sh
      - name: Install detox dependencies
        script: |
          brew tap wix/brew
          brew install applesimutils
      # Install API and dependencies
      - name: Run Postgres
        script: |
          ./scripts/codemagic/install_postgres.sh
      - name: Run PgBouncer
        script: |
          ./scripts/codemagic/install_pgbouncer.sh
      - name: Run MongoDb
        script: |
          ./scripts/codemagic/install_mongodb.sh
      - name: Run Valkey (Redis)
        script: |
          ./scripts/codemagic/install_valkey.sh
      - name: Pull & Run yulife-api-server (API)
        script: |
          ./scripts/codemagic/pull_run_api_server.sh
      - name: Pull last allure report
        script: |
          ./scripts/codemagic/pull_latest_allure_report.sh
      - name: Run detox test
        script: |
          ./scripts/codemagic/run_detox_test.sh
      - name: Upload results
        script: |
          ./scripts/codemagic/upload_detox_report.sh
    artifacts:
      - e2e-report

  ios-detox-smoke-test:
    <<: *ios_detox_base_test
    name: iOS Detox Smoke Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        DETOX_TEST_TYPE: smoke

  ios-detox-admin:
    <<: *ios_detox_base_test
    name: iOS Detox Admin Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        DETOX_TEST_TYPE: admin

  ios-detox-admin-2:
    <<: *ios_detox_base_test
    name: iOS Detox Admin 2 Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        DETOX_TEST_TYPE: admin:2

  ios-detox-admin-jp:
    <<: *ios_detox_base_test
    name: iOS Detox Admin JP Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        API_REGION: JP
        DETOX_TEST_TYPE: admin
        TARGET_LOCALE: ja-JP

  ios-detox-activity:
    <<: *ios_detox_base_test
    name: iOS Detox Activity Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        DETOX_TEST_TYPE: activity

  ios-detox-activity-2:
    <<: *ios_detox_base_test
    name: iOS Detox Activity 2 Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        DETOX_TEST_TYPE: activity:2

  ios-detox-activity-jp:
    <<: *ios_detox_base_test
    name: iOS Detox Activity JP Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        API_REGION: JP
        DETOX_TEST_TYPE: activity
        TARGET_LOCALE: ja-JP

  ios-detox-battle-pass:
    <<: *ios_detox_base_test
    name: iOS Detox Battle Pass Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        DETOX_TEST_TYPE: battle-pass

  ios-detox-battle-pass-jp:
    <<: *ios_detox_base_test
    name: iOS Detox Battle Pass JP Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        API_REGION: JP
        DETOX_TEST_TYPE: battle-pass
        TARGET_LOCALE: ja-JP

  ios-detox-benefits:
    <<: *ios_detox_base_test
    name: iOS Detox Benefits Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        DETOX_TEST_TYPE: benefits

  ios-detox-benefits-jp:
    <<: *ios_detox_base_test
    name: iOS Detox Benefits JP Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        API_REGION: JP
        DETOX_TEST_TYPE: benefits
        TARGET_LOCALE: ja-JP

  ios-detox-challenges:
    <<: *ios_detox_base_test
    name: iOS Detox Challenges Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        DETOX_TEST_TYPE: challenges

  ios-detox-challenges-2:
    <<: *ios_detox_base_test
    name: iOS Detox Challenges 2 Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        DETOX_TEST_TYPE: challenges:2

  ios-detox-challenges-jp:
    <<: *ios_detox_base_test
    name: iOS Detox Challenges JP Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        API_REGION: JP
        DETOX_TEST_TYPE: challenges
        TARGET_LOCALE: ja-JP

  ios-detox-challenges-extended:
    <<: *ios_detox_base_test
    name: iOS Detox Challenges Extended Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        DETOX_TEST_TYPE: challenges-extended

  ios-detox-challenges-extended-jp:
    <<: *ios_detox_base_test
    name: iOS Detox Challenges Extended JP Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        API_REGION: JP
        DETOX_TEST_TYPE: challenges-extended
        TARGET_LOCALE: ja-JP

  ios-detox-healthcheck:
    <<: *ios_detox_base_test
    name: iOS Detox Healthcheck Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        DETOX_TEST_TYPE: healthcheck

  ios-detox-personal:
    <<: *ios_detox_base_test
    name: iOS Detox Personal Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        DETOX_TEST_TYPE: personal

  ios-detox-personal-jp:
    <<: *ios_detox_base_test
    name: iOS Detox Personal JP Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        API_REGION: JP
        DETOX_TEST_TYPE: personal
        TARGET_LOCALE: ja-JP

  ios-detox-screenshots:
    <<: *ios_detox_base_test
    name: iOS Detox Screenshots Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        DETOX_TEST_TYPE: screenshots

  ios-detox-sa:
    <<: *ios_detox_base_test
    name: iOS Detox SA Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        API_REGION: SA
        DETOX_TEST_TYPE: sa

  ios-detox-surveys:
    <<: *ios_detox_base_test
    name: iOS Detox Surveys Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        DETOX_TEST_TYPE: surveys

  ios-detox-surveys-jp:
    <<: *ios_detox_base_test
    name: iOS Detox Surveys JP Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        API_REGION: JP
        DETOX_TEST_TYPE: surveys
        TARGET_LOCALE: ja-JP

  ios-detox-usa:
    <<: *ios_detox_base_test
    name: iOS Detox USA Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        API_REGION: US
        DETOX_TEST_TYPE: usa

  ios-detox-jp:
    <<: *ios_detox_base_test
    name: iOS Detox JP Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        API_REGION: JP
        DETOX_TEST_TYPE: jp
        TARGET_LOCALE: ja-JP

  ios-detox-worlds:
    <<: *ios_detox_base_test
    name: iOS Detox Worlds Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        DETOX_TEST_TYPE: worlds

  ios-detox-worlds-2:
    <<: *ios_detox_base_test
    name: iOS Detox Worlds 2 Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        DETOX_TEST_TYPE: worlds:2

  ios-detox-worlds-jp:
    <<: *ios_detox_base_test
    name: iOS Detox Worlds JP Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        API_REGION: JP
        DETOX_TEST_TYPE: worlds
        TARGET_LOCALE: ja-JP

  ios-detox-yuscreen:
    <<: *ios_detox_base_test
    name: iOS Detox Yuscreen Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        DETOX_TEST_TYPE: yuscreen

  ios-detox-yuscreen-jp:
    <<: *ios_detox_base_test
    name: iOS Detox Yuscreen JP Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        API_REGION: JP
        DETOX_TEST_TYPE: yuscreen
        TARGET_LOCALE: ja-JP

  ios-detox-group-health:
    <<: *ios_detox_base_test
    name: iOS Detox Group Health Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        DETOX_TEST_TYPE: group-health

  ios-detox-group-health-2:
    <<: *ios_detox_base_test
    name: iOS Detox Group Health 2 Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        DETOX_TEST_TYPE: group-health-two

  ios-detox-health:
    <<: *ios_detox_base_test
    name: iOS Detox Health Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        DETOX_TEST_TYPE: health

  ios-detox-health-jp:
    <<: *ios_detox_base_test
    name: iOS Detox Health JP Test
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        API_REGION: JP
        DETOX_TEST_TYPE: health
        TARGET_LOCALE: ja-JP

  ios-detox-combine-overnight-reports:
    name: iOS Detox Combine Overnight Reports
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      <<: *ios_detox_base_environment
      vars:
        <<: *ios_detox_base_env_vars
        # QA_ALERTS_SLACK_WEBHOOK_URL is already set in Codemagic
    scripts:
      - name: Combine Overnight Reports
        script: |
          ./scripts/codemagic/combine-overnight-detox-reports.sh
