sonar.projectKey=yu-life_yulife-rn-client
sonar.organization=yulife

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=yulife-rn-client
#sonar.projectVersion=SET_BY_CI

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=./src/

sonar.exclusions=src/components/storybook/**,node_modules/**,**/*.spec.ts,build/**,*.sql,e2e/**,scripts/**,assets/**,src/graphql/_core/schema.json,src/graphql/_core/schema/**
