query GetStatistics($userId: String) {
  getStatistics(userId: $userId) {
    current {
      avatar {
        id
        uri
      }
      level
      yuniversalMap
      fullName
      shortName
      sections {
        general {
          title
          subtitle
          stats {
            ...UserStatisticDetails
          }
        }
        duels {
          title
          subtitle
          stats {
            ...UserStatisticDetails
          }
        }
        activity {
          title
          subtitle
          stats {
            ...UserStatisticDetails
          }
        }
      }
    }
    opponent {
      avatar {
        id
        uri
      }
      level
      yuniversalMap
      fullName
      shortName
      sections {
        activity {
          title
          subtitle
          stats {
            ...UserStatisticDetails
          }
        }
      }
    }
  }
  gifting: getOptionsForGift {
    id
    enabled
  }
}
