fragment HealthSmokingState on HealthSmokingState {
  autoClaimedStreakDaysCopy
  heading
  headerButtonText
  backgroundColour
  backgroundImage {
    ...RemoteImage
  }
  streakCarousel {
    id
    position
    status
    title
    titleColour
    backgroundColour
    icon {
      ...RemoteImage
    }
    overlayIcon {
      ...RemoteImage
    }
    buttonLabel
    onPress {
      ...SduiAction
    }
  }
  smokingStreakCarousel {
    id
    status
    title
    titleColour
    backgroundColour
    icon {
      ...RemoteImage
    }
    buttonLabel
    onPress {
      ...SduiAction
    }
    tips {
      id
      title
      description
      icon {
        ...RemoteImage
      }
    }
  }
  streakPastMax
  currentStreak
  lastStreakUpdate
  maxStreak
  journeySoFarHeading
  milestoneCarousel {
    id
    image {
      ...RemoteImage
    }
    completed
    popup {
      title
      description
      tips {
        id
        title
        description
        icon {
          ...RemoteImage
        }
      }
      label
      cta
    }
  }
  totalAvoided {
    image {
      ...RemoteImage
    }
    title
    value
  }
  totalSaved {
    image {
      ...RemoteImage
    }
    title
    value
  }
  sponsorship {
    title
    description
    cta
    backgroundImage {
      ...RemoteImage
    }
  }
  tips {
    id
    title
    description
    icon {
      ...RemoteImage
    }
  }
  triggers {
    label
    value
  }
  defaultTriggers {
    label
    value
  }
  customTriggers {
    label
    value
  }
  triggersCopy {
    edit {
      title
      description
      cta
    }
  }
  reasons {
    label
    value
  }
  defaultReasons {
    label
    value
  }
  customReasons {
    label
    value
  }
  reasonsCopy {
    edit {
      title
      description
      cta
    }
  }
  showStreakCheckInOverlay
  streakCheckInOverlay {
    title
    failCta
    continueCta
    celebration {
      title
      description
      cta
      tips {
        id
        title
        description
        icon {
          ...RemoteImage
        }
      }
      chipsTitle
      chips {
        label
        value
        colour
      }
      yuCoinAwarded
    }
    showMilestoneUnlocked
    milestoneUnlocked {
      title
      description
      colour
      image {
        ...RemoteImage
      }
      statistics
      infoBox {
        title
        description
      }
      days
      cta
    }
    showLastMilestoneCelebration
    lastMilestoneCelebration {
      title
      image {
        ...RemoteImage
      }
      description
      cta
      buttonAction {
        ...SduiAction
      }
    }
  }
  streakLapsedAction {
    ...SduiAction
  }
  optOutText
  optOutModal {
    image {
      ...RemoteImage
    }
    title
    description
    buttonText
    buttonAction {
      ...SduiAction
    }
    backButtonText
  }
  isActive
  updatedToday
  streakProgressAnimation {
    items {
      start
      end
      animation
    }
  }
  gameIntroModal {
    title
    ctaLabel
    image {
      ...VariableRemoteImage
    }
    displayDuration
    closeOnBlur
    onDismiss {
      ...SduiAction
    }
  }
  cravingsManaged
  gameOptions {
    timer {
      enableMinuteAdditionAnimation
      enableMinutePulseAnimation
      enableMinuteHapticsImpact
      displayColor
      triggers {
        seconds
        repeat
        color
        pulseColor
        action {
          ...SduiAction
        }
      }
    }
    screens {
      overlays {
        state
        timer {
          min
          max
        }
        image {
          ...VariableRemoteImage
        }
        displayImage
        spotlight
        copy {
          title
          info
          description
        }
        allowRestart
      }
    }
  }
}
