fragment HealthSmokingState on HealthSmokingState {
    currentStreak
    heading
    headerButtonText
    streakCarousel {
        id
        title
        completed
    }
    journeySoFarHeading
    milestoneCarousel {
        id
        title
        completed
    }
    showStreakCheckInOverlay
    streakCheckInOverlay {
      title
      failCta
      continueCta
      celebration {
        title
        description
        cta
      }
      showMilestoneUnlocked
      milestoneUnlocked {
        title
        image {
          ...RemoteImage
        }
        statistics
        infoBox {
          title
          description
        }
        days
        cta
      }
    }
    totalAvoided {
        image {
            ...RemoteImage
        }
        title
        value
    }
    totalSaved {
        image {
            ...RemoteImage
        }
        title
        value
    }
    triggers
    reasons
    optOutText
    optOutModal {
      image {
        ...RemoteImage
      }
      title
      description
      buttonText
      buttonAction {
        ...SduiAction
      }
      backButtonText
    }
    isActive
    updatedToday
}
