fragment HealthSmokingState on HealthSmokingState {
    heading
    streakCarousel {
        id
        title
        completed
    }
    journeySoFarHeading
    milestoneCarousel {
        id
        title
        completed
    }
    totalAvoided {
        title
        value
    }
    totalSaved {
        title
        value
    }
    triggers
    reasons
    optOutText
    optOutModal {
        image {
            ...RemoteImage
        }
        title
        description
        buttonText
        buttonAction {
            ...SduiAction
        }
        backButtonText
    }
    updatedToday
}
