import { IDatabaseItem, generateRandomMongoId } from "@yu-life/yulife-bdd-framework";

export const AUTH_TEMPLATE = {
    type: "mongo",
    modelName: "authpassword",
    data: {
        userId: generateRandomMongoId(),
        attempts: 1,
        lastAttempt: "2019-03-12T14:10:29.275+00:00",
        lastIp: "35.176.60.174",
        password: "letmein",
        scope: "user",
        strategy: "0",
        used: false,
    },
} as IDatabaseItem;

export const allTogglesTrueFor_PLI = {
    type: "mongo",
    modelName: "usertoggles",
    data: {
        _id: generateRandomMongoId(),
        userId: generateRandomMongoId(),
        features: {
            showNotifications: true,
            showStreaks: true,
            showCounter: true,
            showBuildNumber: true,
            showSettings: true,
            disableUserEntries: true,
            fitbit: true,
            showConnections: true,
            showLastSynced: true,
            newPassiveValidationRule: true,
            usePassiveMeditation: true,
            statsShowCoinGeneralTotalYearned: true,
            statsShowCoinRecommendationCard: true,
            statsShowCoinGeneralTotalRedeemedCard: true,
            statsShowCoinAchievementCard: true,
            statsShowChallengeGeneralCard: true,
            statsShowChallengeRecommendationCard: true,
            statsShowChallengeComparisonCard: true,
            statsShowStepsRecommendationCard: true,
            statsShowStepsGeneralCard: true,
            statsShowStepsBestScoreCard: true,
            statsShowStepsGraphCard: true,
            statsShowMindfulnessRecommendationCard: true,
            statsShowMindfulnessGeneralCard: true,
            statsShowMindfulnessBestScoreCard: true,
            statsShowMindfulnessGraphCard: true,
            statsShowCyclingRecommendationCard: true,
            statsShowCyclingGeneralCard: true,
            statsShowCyclingBestScoreCard: true,
            statsShowCyclingGraphCard: true,
            showStats: true,
            showDuels: true,
            showCommunityGoals: true,
            showReferrals: true,
            yuScreenV3: true,
            hasCoveaFibActive: true,
            hasBupaDentActive: true,
            showDailyScreenCustomIcon: true,
            showYucoinPowerButton: true,
        },
    },
} as IDatabaseItem;
