fragment APIConfig on APIConfig {
  language
  stripeKey
  mixpanelKey
  mixpanelBaseUrl
  enabledCaptchaProviders
  hcaptchaSiteKey
  urls {
    members
    forgotPassword
    website
    privacyPolicy
    rewardsPolicy
    eula
  }
  intercom {
    appId
    ios
    android
  }
  customerio {
    apiKey
    siteId
    region
  }
  datadog {
    appId
    appKey
    site
    trackUserInteractions
    trackXHRs
    trackErrors
  }
  sduiStaticDeeplinks {
    name
    stepId
    dynamicRouteId
  }
  sduiJourney {
    supportRequest
  }
  sessionTimeout
}
