fragment HeroCard on HeroCard {
  id
  badge {
    text
    icon
  }
  header {
    heading
    image {
      ...RemoteImage
    }
    subheading {
      text
      icon
    }
    button {
      text
      icon
      state
    }
  }
  body {
    progress {
      currentProgress
      maxProgress
      milestones {
        progress
        state
      }
    }
    image
    backgroundImage {
      ...RemoteImage
    }
  }
  footer {
    left {
      text
      icon
    }
    right {
      text
      icon
    }
  }
  onPress {
    ...SduiAction
  }
  activePeriod {
    startDate
    endDate
  }
}
