fragment User on User {
  __typename
  id
  archived
  firstName
  lastName
  fullName
  createdAt
  redeemedOnboarding
  businessAccountId
  challengesDoneToday
  dailyChallengeAmountAvailable
  connections {
    name
    isConnected
    lastUpdated
  }
  userFeatures {
    name
    value
  }
  mobileConsent {
    mobileHealth
    marketing
    pushNotifications
    companyLeaderboard
    workspaceLeaderboard
  }
  passiveSteps: passiveChallenge {
    exchange {
      yucoin
      steps
      meditation
      surge
    }
    levelSlot {
      id
      milestones {
        id
        coins
      }
    }
  }
  passiveMeditation: passiveChallenge(id: MEDITATION) {
    exchange {
      yucoin
      steps
      meditation
      surge
    }
    levelSlot {
      id
      subtype
      unit
      milestones {
        id
        XP
        coins
        target {
          steps
          meditation
        }
      }
    }
  }
  passiveCycling: passiveChallenge(id: CYCLING) {
    levelSlot {
      id
      subtype
      unit
      milestones {
        id
        XP
        coins
        target {
          steps
          meditation
          distance
        }
      }
    }
  }
  leaderboards {
    leaderboardId
    name
    metric
    days
    consent
    hasAccepted
    inviteFrom
  }
  supportConfig {
    supportLevel
  }
}
