fragment UserProfileEvents on UserProfileEvents {
  id
  __typename
  stageId
  participationId
  title
  description
  image {
    uri
  }
  startDate
  endDate
  status
  challenges {
    description
    icon {
      uri
    }
  }
  tags {
    tag
    joined
    icon {
      uri
    }
  }
  joined
  badge {
    text
    icon {
      uri
    }
    backgroundColor
  }
  progressBar {
    max
    current
  }
  milestones {
    targetValue
    image {
      uri
    }
    animated
    rewardId
    rewardClaimed
    isClaimable
  }
  onPress {
    ...SduiAction
  }
  type
}
