fragment UserActiveChallenge on ActiveChallenge {
  challenge {
    id
    level
    levelSlotId
    levelSlotTemplateId
    status
    endDateTime
    startDateTime
    createdBySource
    rating
    subtype
    yuCoinAwarded
    yuniversalMap
    incomingData {
      steps
      meditation
      distance
      duration
      calories
    }
  }
  levelSlot {
    subtype
    unit
    shouldEndOnLastGoalAchieved
    fitKitTypes
    yuHealth {
      dataType
      capabilities
    }
    milestones {
      id
      XP
      coins
      target {
        steps
        meditation
        distance
        duration
        calories
      }
    }
  }
}
