fragment User on User {
  __typename
  id
  archived
  firstName
  lastName
  fullName
  dateOfBirth
  createdAt
  redeemedOnboarding
  businessAccountId
  challengesDoneToday
  dailyChallengeAmountAvailable
  connections {
    name
    isConnected
    lastUpdated
  }
  userFeatures {
    name
    value
  }
  mobileConsent {
    mobileHealth
    marketing
    pushNotifications
    companyLeaderboard
    workspaceLeaderboard
  }
  passiveSteps: passiveChallenge {
    exchange {
      yucoin
      steps
      meditation
      surge
    }
    levelSlot {
      id
      milestones {
        id
        coins
      }
    }
  }
  passiveMeditation: passiveChallenge(id: MEDITATION) {
    exchange {
      yucoin
      steps
      meditation
      surge
    }
    levelSlot {
      id
      subtype
      unit
      milestones {
        id
        XP
        coins
        target {
          steps
          meditation
        }
      }
    }
  }
  passiveCycling: passiveChallenge(id: CYCLING) {
    levelSlot {
      id
      subtype
      unit
      milestones {
        id
        XP
        coins
        target {
          steps
          meditation
          distance
        }
      }
    }
  }
  activeChallenge {
    challenge {
      id
      level
      levelSlotId
      status
      endDateTime
      startDateTime
      rating
      subtype
      yuCoinAwarded
      incomingData {
        steps
        meditation
        distance
        duration
      }
    }
    levelSlot {
      subtype
      unit
      shouldEndOnLastGoalAchieved
      fitKitTypes
      milestones {
        id
        XP
        coins
        target {
          steps
          meditation
          distance
          duration
          calories
        }
      }
    }
  }
  activeStreak {
    id
    type
    value
    maxStreak
    streakAwardId
    streak
    nextStreakAvailableAt
  }
  todayActivity {
    id
    earned
    milestones
    name
    score
  }
  leaderboards {
    leaderboardId
    name
    metric
    days
    consent
    hasAccepted
    inviteFrom
  }
}
