import { IDatabaseItem, generateRandomMongoId } from "@yu-life/yulife-bdd-framework";
import moment from "moment";

export const AUTH_TEMPLATE = {
  type: "mongo",
  modelName: "authpassword",
  data: {
    userId: generateRandomMongoId(),
    attempts: 1,
    lastAttempt: "2019-03-12T14:10:29.275+00:00",
    lastIp: "35.176.60.174",
    password: "letmein",
    scope: "user",
    strategy: "0",
    used: false,
  },
} as IDatabaseItem;

export const allTogglesTrue = {
  type: "mongo",
  modelName: "usertoggles",
  data: {
    _id: generateRandomMongoId(),
    userId: generateRandomMongoId(),
    features: {
      showStreaks: true,
      showCounter: true,
      showBuildNumber: true,
      showSettings: true,
      disableUserEntries: true,
      fitbit: true,
      showConnections: true,
      showLastSynced: true,
      newPassiveValidationRule: true,
      usePassiveMeditation: true,
      statsShowCoinGeneralTotalYearned: true,
      statsShowCoinRecommendationCard: true,
      statsShowCoinGeneralTotalRedeemedCard: true,
      statsShowCoinAchievementCard: true,
      statsShowChallengeGeneralCard: true,
      statsShowChallengeRecommendationCard: true,
      statsShowChallengeComparisonCard: true,
      statsShowStepsRecommendationCard: true,
      statsShowStepsGeneralCard: true,
      statsShowStepsBestScoreCard: true,
      statsShowStepsGraphCard: true,
      statsShowMindfulnessRecommendationCard: true,
      statsShowMindfulnessGeneralCard: true,
      statsShowMindfulnessBestScoreCard: true,
      statsShowMindfulnessGraphCard: true,
      statsShowCyclingRecommendationCard: true,
      statsShowCyclingGeneralCard: true,
      statsShowCyclingBestScoreCard: true,
      statsShowCyclingGraphCard: true,
      showStats: true,
      showDuels: true,
      showCommunityGoals: true,
      rewardRedemptionDisabled: false,
      showYucoinPowerButton: true,
      showBrainGameSudoku: true,
      useNewLeaderboardServices: true,
      enableChallengeBonuses: true,
    },
  },
} as IDatabaseItem;

export const CHALLENGE_TEMPLATE = {
  type: "mongo",
  modelName: "challenge",
  data: {
    _id: generateRandomMongoId(),
    challengeTemplateId: [],
    data: [],
    actions: [],
    target: [],
    userId: "",
    level: 1,
    levelId: "YU_LEVEL_0001",
    levelSlotId: "YU_LEVEL_0001_1",
    levelSlotTemplateId: "SHORT_STROLL_001",
    subtype: "short stroll",
    isNewType: true,
    status: "completed",
    passive: false,
    incomingData: {
      steps: 125,
    },
    startTime: moment().subtract(1, "day").toDate(),
    startDateTime: moment().subtract(1, "day").toDate(),
    endDateTime: moment().subtract(1, "day").toDate(),
    yuCoinAwarded: 60,
    milestoneLog: [
      {
        completionData: [],
        _id: generateRandomMongoId(),
        id: "YU_MILESTONE_SS0001_0",
        completed: moment().subtract(1, "day").toDate(),
        data: {
          steps: 108,
          meditation: 0,
          distance: 0,
        },
        yuCoinAwarded: 60,
      },
    ],
    rating: 3,
    multiplierId: null,
  },
} as IDatabaseItem;

export const allTogglesTrueFor_PLI = {
  type: "mongo",
  modelName: "usertoggles",
  data: {
    _id: generateRandomMongoId(),
    userId: generateRandomMongoId(),
    features: {
      showStreaks: true,
      showCounter: true,
      showBuildNumber: true,
      showSettings: true,
      disableUserEntries: true,
      fitbit: true,
      showConnections: true,
      showLastSynced: true,
      newPassiveValidationRule: true,
      usePassiveMeditation: true,
      statsShowCoinGeneralTotalYearned: true,
      statsShowCoinRecommendationCard: true,
      statsShowCoinGeneralTotalRedeemedCard: true,
      statsShowCoinAchievementCard: true,
      statsShowChallengeGeneralCard: true,
      statsShowChallengeRecommendationCard: true,
      statsShowChallengeComparisonCard: true,
      statsShowStepsRecommendationCard: true,
      statsShowStepsGeneralCard: true,
      statsShowStepsBestScoreCard: true,
      statsShowStepsGraphCard: true,
      statsShowMindfulnessRecommendationCard: true,
      statsShowMindfulnessGeneralCard: true,
      statsShowMindfulnessBestScoreCard: true,
      statsShowMindfulnessGraphCard: true,
      statsShowCyclingRecommendationCard: true,
      statsShowCyclingGeneralCard: true,
      statsShowCyclingBestScoreCard: true,
      statsShowCyclingGraphCard: true,
      showStats: true,
      showDuels: true,
      showCommunityGoals: true,
      showReferrals: true,
      yuScreenV3: true,
      hasCoveaFibActive: true,
      hasBupaDentActive: true,
      showDailyScreenCustomIcon: true,
      showYucoinPowerButton: true,
      enableChallengeBonuses: true,
    },
  },
} as IDatabaseItem;

export const mediaContentToggle = {
  type: "mongo",
  modelName: "usertoggles",
  data: {
    _id: generateRandomMongoId(),
    userId: generateRandomMongoId(),
    features: {
      showStreaks: true,
      showCounter: true,
      showBuildNumber: true,
      showSettings: true,
      disableUserEntries: true,
      fitbit: true,
      showConnections: true,
      showLastSynced: true,
      newPassiveValidationRule: true,
      usePassiveMeditation: true,
      statsShowCoinGeneralTotalYearned: true,
      statsShowCoinRecommendationCard: true,
      statsShowCoinGeneralTotalRedeemedCard: true,
      statsShowCoinAchievementCard: true,
      statsShowChallengeGeneralCard: true,
      statsShowChallengeRecommendationCard: true,
      statsShowChallengeComparisonCard: true,
      statsShowStepsRecommendationCard: true,
      statsShowStepsGeneralCard: true,
      statsShowStepsBestScoreCard: true,
      statsShowStepsGraphCard: true,
      statsShowMindfulnessRecommendationCard: true,
      statsShowMindfulnessGeneralCard: true,
      statsShowMindfulnessBestScoreCard: true,
      statsShowMindfulnessGraphCard: true,
      statsShowCyclingRecommendationCard: true,
      statsShowCyclingGeneralCard: true,
      statsShowCyclingBestScoreCard: true,
      statsShowCyclingGraphCard: true,
      showStats: true,
      showDuels: true,
      showCommunityGoals: true,
      passiveCyclingEnabled: true,
      newMediaPlayer: true,
      useNewLeaderboardServices: true,
      showYucoinPowerButton: true,
      showBrainGameSudoku: true,
      showFiit: true,
      enableChallengeBonuses: true,
    },
  },
} as IDatabaseItem;

export const allTogglesTrueFor_PLI_V4 = {
  type: "mongo",
  modelName: "usertoggles",
  data: {
    _id: generateRandomMongoId(),
    userId: generateRandomMongoId(),
    features: {
      showBuildNumber: true,
      showSettings: true,
      familyIncomeBenefits: true,
      disableUserEntries: true,
      showLastSynced: true,
      statsShowCoinRecommendationCard: true,
      statsShowCyclingRecommendationCard: true,
      statsShowCyclingGeneralCard: true,
      statsShowCyclingBestScoreCard: true,
      statsShowCyclingGraphCard: true,
      showSurge: true,
      newGamePlus: true,
      showReferrals: true,
      yuScreenV3: true,
      showRewardStoreSelection: true,

      hasCoveaFibActive: true,
      hasBupaDentActive: true,
      showDailyScreenCustomIcon: true,
      showYucoinPowerButton: true,
      enableChallengeBonuses: true,
    },
  },
} as IDatabaseItem;

export const DEFAULT_TOGGLES = {
  type: "mongo",
  modelName: "usertoggles",
  data: {
    _id: generateRandomMongoId(),
    userId: generateRandomMongoId(),
    features: {
      showStreaks: true,
      showCounter: true,
      showBuildNumber: true,
      showSettings: true,
      disableUserEntries: true,
      fitbit: true,
      showConnections: true,
      showLastSynced: true,
      newPassiveValidationRule: true,
      usePassiveMeditation: true,
      statsShowCoinGeneralTotalYearned: true,
      statsShowCoinRecommendationCard: true,
      statsShowCoinGeneralTotalRedeemedCard: true,
      statsShowCoinAchievementCard: true,
      statsShowChallengeGeneralCard: true,
      statsShowChallengeRecommendationCard: true,
      statsShowChallengeComparisonCard: true,
      statsShowStepsRecommendationCard: true,
      statsShowStepsGeneralCard: true,
      statsShowStepsBestScoreCard: true,
      statsShowStepsGraphCard: true,
      statsShowMindfulnessRecommendationCard: true,
      statsShowMindfulnessGeneralCard: true,
      statsShowMindfulnessBestScoreCard: true,
      statsShowMindfulnessGraphCard: true,
      statsShowCyclingRecommendationCard: true,
      statsShowCyclingGeneralCard: true,
      statsShowCyclingBestScoreCard: true,
      statsShowCyclingGraphCard: true,
      showStats: true,
      hideSmartHealthScreen: true,
      hideYuMatterScreen: false,
      newGamePlus: true,
      unitySurge: true,
      rewardRedemptionDisabled: false,
      showNotificationCentre: true,
      newMediaPlayer: true,
      showYucoinPowerButton: true,
      showBrainGameSudoku: true,
      showFiit: true,
      useNewLeaderboardServices: true,
      enableChallengeBonuses: true,
      showYumojiHeadwear: true,
    },
  },
} as IDatabaseItem;
