source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby File.read('.ruby-version').strip

gem 'cocoapods', '~> 1.14.3'
gem 'cocoapods-bugsnag', "~> 2.3"
gem 'activesupport', '~> 7.1', '>= 7.1.2'
gem 'cocoapods-patch',  '>= 1.3.0'
gem 'plist'
gem "fastlane"
