export interface USProductData {
    id: string,
    slotAbreviation?: string,
    heading: string,
    description: string,
    shortDescription?: string,
    image_1: string,
    markdownTitle_1: string,
    markdownSubTitle_1: string,
    image_2: string,
    markdownTitle_2: string,
    markdownSubTitle_2: string,
    image_3: string,
    markdownTitle_3: string,
    markdownSubTitle_3: string,
    videoImageUrl?: string,
    videoUrl?: string,
    footerText?: string,
    legalStuff_1?: string,
    legalStuff_2?: string,
    legalStuff_3?: string,
    legalStuff_4?: string,
    legalStuff_5?: string,
    middleImage?: string,
    titleMarkdown: string;
    
}