.ios-build-cache:
  cache: &ios-build-cache
    policy: pull-push
    key:
      files:
        - pnpm-lock.yaml
        - support/ios/Podfile.lock
      prefix: "${MACOS_VM_IMAGE_VERSION}-${IOS_XCODE_VERSION}-ios-build"
    paths:
      # https://pnpm.io/continuous-integration#gitlab-ci
      - $PNPM_HOME/store
      - $COREPACK_HOME
      - .cocoapods_cache

.ios-pre-build:
  script:
    - nvm install -b
    - corepack enable
    - pnpm install --frozen-lockfile
    - pnpm tsc
    - node ./scripts/replace-package-versionCodes.js "$CI_PIPELINE_IID"
    # Generate native projects
    - EXPO_NO_GIT_STATUS=1 EXPO_NO_DOTENV=1 npx expo prebuild --platform "$PLATFORM" --clean --no-install
    # Install CocoaPods dependencies
    - cd ios
    - bundle config frozen true
    - bundle install
    - bundle exec pod install --repo-update --deployment
    - cd ..
    # Set watch display name
    - ./scripts/set-watch-display-name.sh "$DISPLAY_NAME"
    # Log info.plist
    - cat ios/YuLife/Info.plist
    # Download secure files (App Store Connect API Key)
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash

ios-develop-build:
  extends:
    - .assume-aws-role-with-web-identity:devops:develop-builds
    - .base-macos-vm
  stage: build
  interruptible: false
  cache:
    <<: *ios-build-cache
  variables:
    # Fastlane variables
    FL_APP_IDENTIFIER: com.yulife.develop
    FL_WATCH_APP_IDENTIFIER: com.yulife.develop.yuwatch
    FL_TEAM_ID: 739BJV2T6V
    FL_IOS_CERT_TYPE: adhoc
    FL_IOS_EXPORT_METHOD: ad-hoc
    FL_MATCH_S3_BUCKET: yu-develop-react-native-certificates
    MATCH_PASSWORD: $FL_DEVELOP_MATCH_PASSWORD
    SPACESHIP_CONNECT_API_KEY_FILEPATH: $SPACESHIP_CONNECT_DEVELOPER_API_KEY_FILEPATH
    SPACESHIP_CONNECT_API_KEY_ID: $SPACESHIP_CONNECT_DEVELOPER_API_KEY_ID
    # Expo variables
    ENVFILE: ".env.develop"
    BUNDLE_ID: com.yulife.develop
    PLATFORM: ios
    ENABLE_YUWATCH: 1
    # Project variables
    # Set cocoapods cache path to local folder to allow gitlab cache it
    CP_HOME_DIR: "$CI_PROJECT_DIR/.cocoapods_cache"
  script:
    - !reference [.ios-pre-build, script]
    # Build ipa for distribution
    - fastlane ios develop_build
  artifacts:
    paths:
      - builds/ios/
      - build-logs/
    expire_in: 15 days
    when: always
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" && $CI_PIPELINE_SOURCE != "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true

ios-uat-build:
  extends:
    - .assume-aws-role-with-web-identity:devops:develop-builds
    - .base-macos-vm
  stage: build
  interruptible: false
  variables:
    # Fastlane variables
    FL_APP_IDENTIFIER: com.yulife.develop
    FL_WATCH_APP_IDENTIFIER: com.yulife.develop.yuwatch
    FL_TEAM_ID: 739BJV2T6V
    FL_IOS_CERT_TYPE: appstore
    FL_IOS_EXPORT_METHOD: app-store
    FL_MATCH_S3_BUCKET: yu-develop-react-native-certificates
    MATCH_PASSWORD: $FL_DEVELOP_MATCH_PASSWORD
    SPACESHIP_CONNECT_API_KEY_FILEPATH: $SPACESHIP_CONNECT_DEVELOPER_API_KEY_FILEPATH
    SPACESHIP_CONNECT_API_KEY_ID: $SPACESHIP_CONNECT_DEVELOPER_API_KEY_ID
    # Expo variables
    ENVFILE: ".env.uat"
    BUNDLE_ID: com.yulife.develop
    PLATFORM: ios
    ENABLE_YUWATCH: 1
    # Project variables
    # Set cocoapods cache path to local folder to allow gitlab cache it
    CP_HOME_DIR: "$CI_PROJECT_DIR/.cocoapods_cache"
  script:
    - !reference [.ios-pre-build, script]
    # Build ipa for distribution
    - fastlane ios uat_build
  artifacts:
    paths:
      - builds/ios/
      - build-logs/
    expire_in: 15 days
    when: always
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release\/.*$/

ios-production-build:
  extends:
    - .assume-aws-role-with-web-identity:devops:production-builds
    - .base-macos-vm
  stage: build
  interruptible: false
  variables:
    # Fastlane variables
    FL_APP_IDENTIFIER: com.yulife.main
    FL_WATCH_APP_IDENTIFIER: com.yulife.main.yuwatch
    FL_TEAM_ID: 739BJV2T6V
    FL_IOS_CERT_TYPE: appstore
    FL_IOS_EXPORT_METHOD: app-store
    FL_MATCH_S3_BUCKET: yu-production-react-native-certificates
    MATCH_PASSWORD: $FL_PRODUCTION_MATCH_PASSWORD
    # Expo variables
    ENVFILE: ".env.production"
    BUNDLE_ID: com.yulife.main
    PLATFORM: ios
    ENABLE_YUWATCH: 1
    # Project variables
    # Set cocoapods cache path to local folder to allow gitlab cache it
    CP_HOME_DIR: "$CI_PROJECT_DIR/.cocoapods_cache"
  script:
    - !reference [.ios-pre-build, script]
    # Build ipa for distribution
    - fastlane ios production_build
  artifacts:
    paths:
      - builds/ios/
      - build-logs/
    expire_in: 15 days
    when: always
  rules:
    - if: $CI_COMMIT_TAG =~ /^release\/.*$/
