build:e2e:
  extends:
    - .generic-node-arm64
    - .cache-pull
  stage: build
  interruptible: true
  script:
    # Install node
    - nvm install -b
    - corepack enable
    - export GITLAB_TOKEN="${CI_JOB_TOKEN}"
    - pnpm install --frozen-lockfile
    - pnpm e2e:build
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - e2e/**/*
