cache:
  key:
    files:
      - "yarn.lock"
      - "patches/**"
  paths:
    - "node_modules/"
    - ".yarn/"
    - "yarn.lock.sha256sum"

.build_cache:
  script:
    # sha256 of yarn file
    - sha256sum yarn.lock > current-sha
    # Current sha256 hash file
    - cat current-sha
    # Check sha256 hash file of cache if not there rebuild else remove files to avoid cache push
    - |
      if ! sha256sum -c yarn.lock.sha256sum; then
        echo "yarn.lock checksum does not match cache"
        mv current-sha yarn.lock.sha256sum
      else
        echo "Cache is the same as before, removing cache files to prevent cache from updating"
        rm -rf node_modules .yarn/ yarn.lock.sha256sum
      fi
