spec:
  inputs:
    detox_test_type:
      type: string
      default: "healthcheck"
      description: "Detox test type to run"
      options:
        - activity
        - activity:2
        - admin
        - admin:2
        - battle-pass
        - benefits
        - challenges
        - challenges-2
        - challenges-extended
        - healthcheck
        - jp
        - overnight
        - personal
        - reward-passes
        - sa
        - screenshots
        - smoke
        - surveys
        - usa
        - worlds
        - worlds-2
        - yuscreen
    api_branch_name:
      type: string
      default: "develop"
      description: "Target API container branch"
---
include:
  - component: $CI_SERVER_FQDN/yu-life/infrastructure/yulife-devops-shared-config/assume-aws-role-with-web-identity@assume-aws-role-with-web-identity-2.0.0
    inputs:
      job_name: assume-aws-role-with-web-identity:qa-reporter
      role_arn: $QA_REPORTER_ROLE_ARN
      duration_seconds: 6000

variables:
  API_BRANCH_NAME: $[[ inputs.api_branch_name ]]

.detox-cache:
  cache: &detox-cache
    policy: pull-push
    key:
      files:
        - support/ios/Gemfile.lock
        - support/ios/Podfile.lock
      prefix: $CI_DETOX_CACHE_PREFIX
    paths:
      - .cocoapods_cache
      - ios/build/Build/Products

.detox-overnight-rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_JOB == "overnight-detox-run"
      interruptible: false
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "overnight"'
      interruptible: false

ios-detox-build-app:
  tags:
    - oakhost_macos_m4
  image: $MACOS_VM_IMAGE
  stage: build
  interruptible: true
  cache:
    <<: *detox-cache
  variables:
    FORCE_COLOR: 1
    GITLAB_TOKEN: $CI_JOB_TOKEN
    CI_DETOX_CACHE_PREFIX: ios-detox-build
    # Configure tart
    TART_EXECUTOR_SHELL: bash -l
    # Set cocoapods cache path to local folder to allow gitlab cache it
    CP_HOME_DIR: "$CI_PROJECT_DIR/.cocoapods_cache"
    BUNDLE_ID: "com.yulife.develop"
    XCODE_WORKSPACE: "YuLife.xcworkspace"
    XCODE_SCHEME: "YuLife"
    DISPLAY_NAME: "YuLife (e2e)"
    ENVFILE: ".env.e2e"
    # This will be the app version (patch)
    BITRISE_BUILD_NUMBER: 1234
    PLATFORM: ios
    ENABLE_YUWATCH: 0
    DETOX_BUILD_CONFIG: ios.sim.release
    FORCE_DETOX_BUILD: "true"
  script:
    - ./scripts/gitlab/detox/build_detox_app.sh
  artifacts:
    paths:
      - detox-build.log
    expire_in: 7 days
    untracked: false
  rules:
    - !reference [.detox-overnight-rules, rules]
    - if: $CI_PIPELINE_SOURCE == "web"
      interruptible: false
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        CI_DETOX_CACHE_PREFIX: ios-detox-build-modified-files
        DETOX_BUILD_CONFIG: ios.sim.debug
        FORCE_DETOX_BUILD: "false"
      changes:
        - e2e/**/*

.base-detox-test:
  extends: .assume-aws-role-with-web-identity:qa-reporter
  tags:
    - oakhost_macos_m4
  image: $MACOS_VM_IMAGE
  stage: test
  timeout: 100m
  interruptible: true
  cache:
    <<: *detox-cache
    policy: pull
  variables:
    FORCE_COLOR: 1
    GITLAB_TOKEN: $CI_JOB_TOKEN
    CI_DETOX_CACHE_PREFIX: ios-detox-build
    # Configure tart
    TART_EXECUTOR_SHELL: bash -l
    # Build env vars
    CP_HOME_DIR: "$CI_PROJECT_DIR/.cocoapods_cache"
    BUNDLE_ID: "com.yulife.develop"
    XCODE_WORKSPACE: "YuLife.xcworkspace"
    XCODE_SCHEME: "YuLife"
    DISPLAY_NAME: "YuLife (e2e)"
    ENVFILE: ".env.e2e"
    # This will be the app version (patch)
    BITRISE_BUILD_NUMBER: 1234
    PLATFORM: ios
    ENABLE_YUWATCH: 0
    DETOX_BUILD_CONFIG: ios.sim.release
    # Detox env vars
    API_REGION: UK
    TARGET_LOCALE: en-GB
    IPHONE_DEVICE: iPhone 16 Pro
    REPORT_S3_BUCKET_NAME: yu-qa-production-reports
    REPORT_DNS_NAME: reports.qa.yulife.engineering
  script:
    - ./scripts/gitlab/detox/install_dependencies.sh
    # Build app if is not in cache
    - ./scripts/gitlab/detox/build_detox_app.sh
    # Run API server
    - ./scripts/gitlab/detox/pull_run_api_server.sh
    # Sync allure history
    - ./scripts/gitlab/detox/pull_latest_allure_report.sh
    - |
      echo "Running detox test"
      set +e
      # Run detox
      ./scripts/gitlab/detox/run_detox_test.sh
      export DETOX_EXIT_CODE=$?
      # Report results
      ./scripts/gitlab/detox/upload_detox_report.sh
  artifacts:
    paths:
      - e2e-report/**/*.log
    expire_in: 7 days
    untracked: false

ios-detox-run-modified-files:
  extends: .base-detox-test
  allow_failure: true
  variables:
    CI_DETOX_CACHE_PREFIX: ios-detox-build-modified-files
    CI_DETOX_CHANGES: "true"
    DETOX_BUILD_CONFIG: ios.sim.debug
    DETOX_TEST_TYPE: modified-files
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - e2e/**/*

# TODO: DEVOPS-4362 - Allow manual triggering of detox tests
ios-detox-healthcheck-test:
  extends: .base-detox-test
  variables:
    DETOX_TEST_TYPE: healthcheck
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "healthcheck"'
      interruptible: false

ios-detox-screenshots:
  extends: .base-detox-test
  variables:
    DETOX_TEST_TYPE: screenshots
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "screenshots"'
      interruptible: false

ios-detox-smoke:
  extends: .base-detox-test
  variables:
    DETOX_TEST_TYPE: smoke
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "smoke"'
      interruptible: false

# The following jobs will be part of the overnight run

ios-detox-admin:
  extends: .base-detox-test
  variables:
    DETOX_TEST_TYPE: admin
  rules:
    - !reference [.detox-overnight-rules, rules]
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "admin"'
      interruptible: false

ios-detox-admin-2:
  extends: .base-detox-test
  variables:
    DETOX_TEST_TYPE: admin:2
  rules:
    - !reference [.detox-overnight-rules, rules]
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "admin:2"'
      interruptible: false

ios-detox-activity:
  extends: .base-detox-test
  variables:
    DETOX_TEST_TYPE: activity
  rules:
    - !reference [.detox-overnight-rules, rules]
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "activity"'
      interruptible: false

ios-detox-activity-2:
  extends: .base-detox-test
  variables:
    DETOX_TEST_TYPE: activity:2
  rules:
    - !reference [.detox-overnight-rules, rules]
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "activity:2"'
      interruptible: false

ios-detox-battle-pass:
  extends: .base-detox-test
  variables:
    DETOX_TEST_TYPE: battle-pass
  rules:
    - !reference [.detox-overnight-rules, rules]
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "battle-pass"'
      interruptible: false

ios-detox-benefits:
  extends: .base-detox-test
  variables:
    DETOX_TEST_TYPE: benefits
  rules:
    - !reference [.detox-overnight-rules, rules]
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "benefits"'
      interruptible: false

ios-detox-challenges:
  extends: .base-detox-test
  variables:
    DETOX_TEST_TYPE: challenges
  rules:
    - !reference [.detox-overnight-rules, rules]
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "challenges"'
      interruptible: false

ios-detox-challenges-2:
  extends: .base-detox-test
  variables:
    DETOX_TEST_TYPE: challenges:2
  rules:
    - !reference [.detox-overnight-rules, rules]
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "challenges:2"'
      interruptible: false

ios-detox-challenges-extended:
  extends: .base-detox-test
  variables:
    DETOX_TEST_TYPE: challenges-extended
  rules:
    - !reference [.detox-overnight-rules, rules]
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "challenges-extended"'
      interruptible: false

ios-detox-personal:
  extends: .base-detox-test
  variables:
    DETOX_TEST_TYPE: personal
  rules:
    - !reference [.detox-overnight-rules, rules]
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "personal"'
      interruptible: false

ios-detox-sa:
  extends: .base-detox-test
  variables:
    DETOX_TEST_TYPE: sa
    API_REGION: SA
  rules:
    - !reference [.detox-overnight-rules, rules]
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "sa"'
      interruptible: false

ios-detox-surveys:
  extends: .base-detox-test
  variables:
    DETOX_TEST_TYPE: surveys
  rules:
    - !reference [.detox-overnight-rules, rules]
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "surveys"'
      interruptible: false

ios-detox-usa:
  extends: .base-detox-test
  variables:
    DETOX_TEST_TYPE: usa
    API_REGION: US
  rules:
    - !reference [.detox-overnight-rules, rules]
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "usa"'
      interruptible: false

ios-detox-jp:
  extends: .base-detox-test
  variables:
    DETOX_TEST_TYPE: jp
    API_REGION: JP
    TARGET_LOCALE: ja-JP
  rules:
    - !reference [.detox-overnight-rules, rules]
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "jp"'
      interruptible: false

ios-detox-worlds:
  extends: .base-detox-test
  variables:
    DETOX_TEST_TYPE: worlds
  rules:
    - !reference [.detox-overnight-rules, rules]
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "worlds"'
      interruptible: false

ios-detox-worlds-2:
  extends: .base-detox-test
  variables:
    DETOX_TEST_TYPE: worlds:2
  rules:
    - !reference [.detox-overnight-rules, rules]
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "worlds:2"'
      interruptible: false

ios-detox-yuscreen:
  extends: .base-detox-test
  variables:
    DETOX_TEST_TYPE: yuscreen
  rules:
    - !reference [.detox-overnight-rules, rules]
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "yuscreen"'
      interruptible: false

ios-detox-reward-passes:
  extends: .base-detox-test
  variables:
    DETOX_TEST_TYPE: reward-passes
  rules:
    - !reference [.detox-overnight-rules, rules]
    - if: '$CI_PIPELINE_SOURCE == "web" && "$[[ inputs.detox_test_type ]]" == "reward-passes"'
      interruptible: false

combine-overnight-detox-reports:
  extends: .base-detox-test
  stage: test-report
  script:
    - ./scripts/gitlab/detox/combine-overnight-detox-reports.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_JOB == "overnight-detox-run"
      when: always
