deploy:dev:storybook:
  extends:
    - .assume-openid-role
    - .base-node-14
  stage: release
  # Do not cancel this job if newer commit made
  interruptible: false
  needs:
    - test
  script:
    - yarn build:storybook:web
    - aws s3 sync ./storybook-static  s3://yu-us-east-1-develop-app-storybook-origin
    - aws cloudfront create-invalidation --distribution-id "E1ZJNSNTXUD7K6" --paths "/*" --region "eu-west-2"
  only:
    refs:
      - develop
