deploy:dev:storybook:
  extends:
    - .assume-openid-role
    - .generic-node
  stage: release
  # Do not cancel this job if newer commit made
  interruptible: false
  variables:
    ROLE_ARN: $APP_COMPONENTS_ROLE_ARN
    CLOUDFRONT_DOMAIN: app-components.yulife.engineering
    CLOUDFRONT_S3_BUCKET: yu-develop-app-components
  needs:
    - test
  script:
    # Install node
    - . "$NVM_DIR/nvm.sh" && nvm install -b
    - corepack enable
    - yarn build:storybook:web
    - aws s3 sync --delete ./storybook-static  "s3://$CLOUDFRONT_S3_BUCKET"
    - |
      DISTRIBUTION_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[*].{id:Id,aliases:Aliases.Items}[?aliases && contains(aliases,'$CLOUDFRONT_DOMAIN')].id" --output text)
      echo "Invalidating Cloudfront Distribution $DISTRIBUTION_ID"
      aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
  only:
    refs:
      - develop
