test:
  extends: .generic-node
  stage: test
  interruptible: true
  script:
    # Install node
    - . "$NVM_DIR/nvm.sh" && nvm install -b
    - corepack enable
    - export GITLAB_TOKEN="${CI_JOB_TOKEN}"
    - yarn install --frozen-lockfile --cache-folder .yarn/
    - yarn test
    # Rebuild cache if needed
    - !reference [.build_cache, script]
  only:
    - merge_requests
    - develop
    - /^release\/.*$/
