test:
  extends: .generic-node-arm64
  stage: test
  interruptible: true
  variables:
    # Increase memory limit for node
    NODE_OPTIONS: "--max_old_space_size=3072"
  script:
    # Install node
    - nvm install -b
    - corepack enable
    - export GITLAB_TOKEN="${CI_JOB_TOKEN}"
    - yarn install --frozen-lockfile
    - yarn test
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_BRANCH =~ /^release\/.*$/
