translate:
  extends:
    - .generic-node-arm64
    - .cache-pull
  stage: translate
  retry: 2
  script:
    # Install node
    - nvm install -b
    - corepack enable
    # Switch from Gitlab SSH to Service User Basic Auth
    - git remote rm origin && git remote add origin https://oauth2:${GITLAB_TOKEN_RELEASE}@gitlab.com/$CI_PROJECT_PATH.git
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"
    - git fetch -q
    - git checkout $CI_COMMIT_REF_NAME
    - pnpm install --frozen-lockfile
    # Push new keys and translate them
    - pnpm translations:push
    # Download, commit and push the translation changes
    - pnpm translations:download
    - git add ./src/locale/translations/downloaded
    - git commit --no-verify -m "Chore - Updated translations" || (echo "No new translations to commit" && exit 0)
    - git push --no-verify
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_JOB == "translate-nightly"
    - if: $CI_COMMIT_BRANCH =~ /^release\/.*$/
      when: manual
