query GetWellbeingHubItems($os: OS, $width: Float, $height: Float, $categories: [String]) {
  listItems: wellbeingHubItems(os: $os, categories: $categories) {
    id
      sduiStepId
      thumbnail {
        id
        uri(options: { width: $width, height: $height, crop: "fit", format: png })
      }
      icon {
        id
        uri
      }
      title
      description
      route
  }
  location: getMobileUserContentLocation {
    hasUserSelectedContentLocation
    location
    locationLabel
  }
  categories: wellbeingHubCategories(os: $os) {
    id
    name
  }
}
