query GetMobileUnlockableBattlePassTeasers {
  targets: getMobileUnlockableBattlePassTeasers {
    hint {
      label
      description
      image {
        ...RemoteImage
      }
      onPress {
        ...SduiAction
      }
    }
    targets {
      id
      notificationIcon {
        ...RemoteImage
      }
      milestones {
        id
        participationId
        quantity
        title
        progress
        target
        primaryColor
        secondaryColor
        overlayColor
        image {
          ...RemoteImage
        }
        overlayImage {
          ...RemoteImage
        }
      }
    }
  }
}
