import { Carrier, ProductCode, generateProductRecords } from "@yu-life/yulife-bdd-framework";
import {
  BUSINESS_ACCOUNT_2,
  BUSINESS_ACCOUNT_4,
  BUSINESS_ACCOUNT_5,
  BUSINESS_ACCOUNT_6,
  BUSINESS_ACCOUNT_GDent_9,
  BUSINESS_ACCOUNT_GHI_8,
} from "./business";
import moment from "moment";
import { GOAL_PRODUCTS_1 } from "../mongo/goal_products";

const format = "YYYY-MM-DDTHH:mm:ssZ";

export const BUSINESS_PRODUCT_4_RGL = generateProductRecords({
  productCode: ProductCode.registeredGroupLife,
  carrier: Carrier.AIG,
  productId: "YUG0000002",
  policyName: "Justice League Policy RGL",
  businessAccountId: BUSINESS_ACCOUNT_4.data.business_account_id,
  startDate: "2020-02-02T00:00:00Z",
});

export const BUSINESS_PRODUCT_4_GIP = generateProductRecords({
  productCode: ProductCode.groupIncomeProtection,
  carrier: Carrier.AIG,
  productId: "YUG0000003",
  policyName: "Justice League Policy GIP",
  businessAccountId: BUSINESS_ACCOUNT_4.data.business_account_id,
  startDate: "2020-02-02T00:00:00Z",
});

export const BUSINESS_PRODUCT_4_GCI = generateProductRecords({
  productCode: ProductCode.groupIncomeProtection,
  carrier: Carrier.AIG,
  productId: "YUG0000004",
  policyName: "Justice League Policy GCI",
  businessAccountId: BUSINESS_ACCOUNT_4.data.business_account_id,
  startDate: "2020-02-02T00:00:00Z",
});

export const BUSINESS_PRODUCT_1_WB = generateProductRecords({
  productCode: ProductCode.wellbeingAccess,
  carrier: Carrier.YuLife,
  productId: "YUG0000005",
  businessAccountId: BUSINESS_ACCOUNT_6.data.business_account_id,
});

export const BUSINESS_PRODUCT_4_GDental = generateProductRecords({
  productCode: ProductCode.groupDentalPlan,
  carrier: Carrier.Bupa,
  productId: "YUG0000006",
  policyName: "Justice League Policy GDental",
  businessAccountId: BUSINESS_ACCOUNT_6.data.business_account_id,
  startDate: "2020-02-02T00:00:00Z",
});

export const BUSINESS_PRODUCT_4_GDental_CHOICE = generateProductRecords({
  productCode: ProductCode.groupDentalChoice,
  carrier: Carrier.Bupa,
  productId: "YUG1020307",
  policyName: "Justice League Policy GDental",
  businessAccountId: BUSINESS_ACCOUNT_6.data.business_account_id,
  startDate: "2020-02-02T00:00:00Z",
});

export const BUSINESS_PRODUCT_5_WB = generateProductRecords({
  productCode: ProductCode.wellbeingAccess,
  carrier: Carrier.YuLife,
  productId: "YUG1210116",
  businessAccountId: BUSINESS_ACCOUNT_5.data.business_account_id,
});

export const BUSINESS_PRODUCT_8_GHI = generateProductRecords({
  productCode: ProductCode.groupHealth,
  carrier: Carrier.Bupa,
  productId: "YUG1010102",
  policyName: "BLYTHSWOOD Policy GHI",
  businessAccountId: BUSINESS_ACCOUNT_GHI_8.data.business_account_id,
  startDate: moment().add(1, "y").format(format),
  product: {
    policy_start_date: moment().add(1, "week").format(format),
    eventStartDate: moment().add(1, "week").format("YYYY-MM-DD"),
    productGoalTag: GOAL_PRODUCTS_1.data.tag,
  },
  quote: {
    business_quote_id: "GOYT9B8HK3",
    external_quote_id: "1234",
    archived: false,
    unit_rate: null,
    provisional_automatic_acceptance_limit: null,
    provisional_yulife_commission: 0.02,
    provisional_negotiated_additional_commission: 0.0,
    provisional_broker_commission: 0.02,
    sum_assured: null,
    number_of_lives: 99,
    annual_premium: 50000.0,
    flex_benefit: true,
    base_earn_rate: 2,
    max_win_win_rebate: 0.0,
    quote_issued_date: moment().subtract(7, "d").format(),
    sales_person: "dfefsdf",
    provisional_payment_frequency: "M",
    provisional_data_upload_frequency: "A",
    deal_type: null,
    type_of_trust: null,
    created_by_id: null,
    created_at: "2023-04-17T16:40:03.214Z",
    modified_by_id: null,
    modified_at: "2023-04-17T16:40:55.126Z",
    technical_guide: null,
    actively_at_work_condition_override: false,
    actively_at_work_condition: null,
    other_event_limits: null,
    overall_event_limit: null,
    sic_code: null,
    previous_insurer: null,
    previously_insured: "unknown",
    base_rate: null,
    optalitix_id: null,
  },
  schedule: {
    business_quote_id: "GOYT9B8HK3",
    external_schedule_id: null,
    pension_scheme_tax_ref: null,
    effective_date: moment().add(1, "y").format("YYYY-MM-DD"),
    anniversary_date: moment().add(11, "m").format("YYYY-MM-DD"),
    automatic_acceptance_limit: null,
    policy_tcs_ref: null,
    created_by_id: null,
    created_at: "2023-04-17T16:40:03.214Z",
    modified_by_id: null,
    modified_at: "2023-04-17T16:40:55.126Z",
    document_key: null,
    payment_frequency: "M",
    data_upload_frequency: "A",
    policy_specific_condition_statements: null,
  },
  period: {
    number_of_lives: 99,
    period_start_date: moment().add(1, "y").format("YYYY-MM-DD"),
    period_end_date: moment().add(2, "y").format("YYYY-MM-DD"),
    annual_premium: 200000.0,
    period_premium: 200000.0,
  },
  invoice: {
    amount: 31780.0,
    date_issued: moment().subtract(1, "w").format(format),
  },
  commissionTerm: {
    broker_commission: 0.02,
    yulife_commission: 0.02,
    negotiated_additional_commission: 0.0,
    true_up_date: "2023-04-17",
    effective_from: "2024-10-16",
    modified_by_id: null,
    created_by_id: null,
    modified_at: "2023-04-17T16:40:03.214Z",
    created_at: "2023-04-17T16:40:03.214Z",
  },
});

export const BUSINESS_PRODUCT_9_GDent = generateProductRecords({
  productCode: ProductCode.groupDentalPlan,
  carrier: Carrier.Bupa,
  productId: "YUG1010103",
  policyName: "BLYTHSWOOD Policy GDental Dependent",
  businessAccountId: BUSINESS_ACCOUNT_GDent_9.data.business_account_id,
  startDate: moment().add(1, "y").format(format),
  product: {
    policy_start_date: moment().add(1, "y").format(format),
  },
  quote: {
    external_quote_id: "1234",
    archived: false,
    unit_rate: null,
    provisional_automatic_acceptance_limit: null,
    provisional_yulife_commission: 0.02,
    provisional_negotiated_additional_commission: 0.0,
    provisional_broker_commission: 0.02,
    sum_assured: null,
    number_of_lives: 99,
    annual_premium: 50000.0,
    flex_benefit: true,
    base_earn_rate: 0,
    max_win_win_rebate: 0.0,
    quote_issued_date: moment().subtract(7, "d").format(),
    sales_person: "dfefsdf",
    provisional_payment_frequency: "M",
    provisional_data_upload_frequency: "A",
    deal_type: null,
    type_of_trust: null,
    created_by_id: null,
    created_at: "2023-04-17T16:40:03.214Z",
    modified_by_id: null,
    modified_at: "2023-04-17T16:40:55.126Z",
    technical_guide: null,
    actively_at_work_condition_override: false,
    actively_at_work_condition: null,
    other_event_limits: null,
    overall_event_limit: null,
    sic_code: null,
    previous_insurer: null,
    previously_insured: "unknown",
    base_rate: null,
    optalitix_id: null,
  },
  schedule: {
    external_schedule_id: null,
    pension_scheme_tax_ref: null,
    effective_date: moment().add(1, "y").format("YYYY-MM-DD"),
    anniversary_date: moment().add(2, "y").format("YYYY-MM-DD"),
    automatic_acceptance_limit: null,
    created_by_id: null,
    created_at: "2023-04-17T16:40:03.214Z",
    modified_by_id: null,
    modified_at: "2023-04-17T16:40:55.126Z",
    document_key: null,
    payment_frequency: "M",
    data_upload_frequency: "A",
    policy_specific_condition_statements: null,
    policy_tcs_ref: "Test",
  },
  period: {
    number_of_lives: 99,
    period_start_date: moment().add(1, "y").format("YYYY-MM-DD"),
    period_end_date: moment().add(2, "y").format("YYYY-MM-DD"),
    annual_premium: 200000.0,
    period_premium: 200000.0,
    period_type: "initial",
  },
  invoice: {
    amount: 31780.0,
    date_issued: moment().format(format),
  },
  commissionTerm: {
    broker_commission: 0.02,
    yulife_commission: 0.02,
    negotiated_additional_commission: 0.0,
    true_up_date: "2023-04-17",
    effective_from: "2024-10-16",
    modified_by_id: null,
    created_by_id: null,
    modified_at: "2023-04-17T16:40:03.214Z",
    created_at: "2023-04-17T16:40:03.214Z",
  },
});

export const BUSINESS_PRODUCT_10_GDent = generateProductRecords({
  productCode: ProductCode.groupDentalPlan,
  carrier: Carrier.Bupa,
  productId: "YUG1010104",
  policyName: "BLYTHSWOOD Policy GDental Dependent",
  businessAccountId: BUSINESS_ACCOUNT_GDent_9.data.business_account_id,
  startDate: moment().add(1, "y").format(format),
  product: {
    policy_start_date: moment().add(1, "y").format(format),
  },
  quote: {
    external_quote_id: "12345",
    archived: false,
    unit_rate: null,
    provisional_automatic_acceptance_limit: null,
    provisional_yulife_commission: 0.02,
    provisional_negotiated_additional_commission: 0.0,
    provisional_broker_commission: 0.02,
    sum_assured: null,
    number_of_lives: 99,
    annual_premium: 50000.0,
    flex_benefit: true,
    base_earn_rate: 0,
    max_win_win_rebate: 0.0,
    quote_issued_date: moment().subtract(7, "d").format(),
    sales_person: "dfefsdf",
    provisional_payment_frequency: "M",
    provisional_data_upload_frequency: "A",
    deal_type: null,
    type_of_trust: null,
    created_by_id: null,
    created_at: "2023-04-17T16:40:03.214Z",
    modified_by_id: null,
    modified_at: "2023-04-17T16:40:55.126Z",
    technical_guide: null,
    actively_at_work_condition_override: false,
    actively_at_work_condition: null,
    other_event_limits: null,
    overall_event_limit: null,
    sic_code: null,
    previous_insurer: null,
    previously_insured: "unknown",
    base_rate: null,
    optalitix_id: null,
  },
  schedule: {
    external_schedule_id: null,
    pension_scheme_tax_ref: null,
    effective_date: moment().add(1, "y").format("YYYY-MM-DD"),
    anniversary_date: moment().add(2, "y").format("YYYY-MM-DD"),
    automatic_acceptance_limit: null,
    created_by_id: null,
    created_at: "2023-04-17T16:40:03.214Z",
    modified_by_id: null,
    modified_at: "2023-04-17T16:40:55.126Z",
    document_key: null,
    payment_frequency: "M",
    data_upload_frequency: "A",
    policy_specific_condition_statements: null,
    policy_tcs_ref: "Test",
  },
  period: {
    number_of_lives: 99,
    period_start_date: moment().add(1, "y").format("YYYY-MM-DD"),
    period_end_date: moment().add(2, "y").format("YYYY-MM-DD"),
    annual_premium: 200000.0,
    period_premium: 200000.0,
    period_type: "initial",
  },
  invoice: {
    amount: 31780.0,
    date_issued: moment().format(format),
  },
  commissionTerm: {
    broker_commission: 0.02,
    yulife_commission: 0.02,
    negotiated_additional_commission: 0.0,
    true_up_date: "2023-04-17",
    effective_from: "2024-10-16",
    modified_by_id: null,
    created_by_id: null,
    modified_at: "2023-04-17T16:40:03.214Z",
    created_at: "2023-04-17T16:40:03.214Z",
  },
});

export const BUSINESS_PRODUCT_11_GDent = generateProductRecords({
  productCode: ProductCode.groupDentalPlan,
  carrier: Carrier.Bupa,
  productId: "YUG1010105",
  policyName: "BLYTHSWOOD Policy GDental Dependent",
  businessAccountId: BUSINESS_ACCOUNT_GDent_9.data.business_account_id,
  startDate: moment().add(1, "y").format(format),
  product: {
    policy_start_date: moment().add(1, "y").format(format),
  },
  quote: {
    external_quote_id: "12345",
    archived: false,
    unit_rate: null,
    provisional_automatic_acceptance_limit: null,
    provisional_yulife_commission: 0.02,
    provisional_negotiated_additional_commission: 0.0,
    provisional_broker_commission: 0.02,
    sum_assured: null,
    number_of_lives: 99,
    annual_premium: 50000.0,
    flex_benefit: true,
    base_earn_rate: 0,
    max_win_win_rebate: 0.0,
    quote_issued_date: moment().subtract(7, "d").format(),
    sales_person: "dfefsdf",
    provisional_payment_frequency: "M",
    provisional_data_upload_frequency: "A",
    deal_type: null,
    type_of_trust: null,
    created_by_id: null,
    created_at: "2023-04-17T16:40:03.214Z",
    modified_by_id: null,
    modified_at: "2023-04-17T16:40:55.126Z",
    technical_guide: null,
    actively_at_work_condition_override: false,
    actively_at_work_condition: null,
    other_event_limits: null,
    overall_event_limit: null,
    sic_code: null,
    previous_insurer: null,
    previously_insured: "unknown",
    base_rate: null,
    optalitix_id: null,
  },
  schedule: {
    external_schedule_id: null,
    pension_scheme_tax_ref: null,
    effective_date: moment().add(1, "y").format("YYYY-MM-DD"),
    anniversary_date: moment().add(2, "y").format("YYYY-MM-DD"),
    automatic_acceptance_limit: null,
    created_by_id: null,
    created_at: "2023-04-17T16:40:03.214Z",
    modified_by_id: null,
    modified_at: "2023-04-17T16:40:55.126Z",
    document_key: null,
    payment_frequency: "M",
    data_upload_frequency: "A",
    policy_specific_condition_statements: null,
    policy_tcs_ref: "Test",
  },
  period: {
    number_of_lives: 99,
    period_start_date: moment().add(1, "y").format("YYYY-MM-DD"),
    period_end_date: moment().add(2, "y").format("YYYY-MM-DD"),
    annual_premium: 200000.0,
    period_premium: 200000.0,
    period_type: "initial",
  },
  invoice: {
    amount: 31780.0,
    date_issued: moment().format(format),
  },
  commissionTerm: {
    broker_commission: 0.02,
    yulife_commission: 0.02,
    negotiated_additional_commission: 0.0,
    true_up_date: "2023-04-17",
    effective_from: "2024-10-16",
    modified_by_id: null,
    created_by_id: null,
    modified_at: "2023-04-17T16:40:03.214Z",
    created_at: "2023-04-17T16:40:03.214Z",
  },
});

export const BUSINESS_PRODUCT_12_GDent = generateProductRecords({
  productCode: ProductCode.groupDentalPlan,
  carrier: Carrier.Bupa,
  productId: "YUG1010106",
  policyName: "BLYTHSWOOD Policy GDental Dependent",
  businessAccountId: BUSINESS_ACCOUNT_GDent_9.data.business_account_id,
  startDate: moment().add(1, "y").format(format),
  product: {
    policy_start_date: moment().add(1, "y").format(format),
  },
  quote: {
    external_quote_id: "12345",
    archived: false,
    unit_rate: null,
    provisional_automatic_acceptance_limit: null,
    provisional_yulife_commission: 0.02,
    provisional_negotiated_additional_commission: 0.0,
    provisional_broker_commission: 0.02,
    sum_assured: null,
    number_of_lives: 99,
    annual_premium: 50000.0,
    flex_benefit: true,
    base_earn_rate: 0,
    max_win_win_rebate: 0.0,
    quote_issued_date: moment().subtract(7, "d").format(),
    sales_person: "dfefsdf",
    provisional_payment_frequency: "M",
    provisional_data_upload_frequency: "A",
    deal_type: null,
    type_of_trust: null,
    created_by_id: null,
    created_at: "2023-04-17T16:40:03.214Z",
    modified_by_id: null,
    modified_at: "2023-04-17T16:40:55.126Z",
    technical_guide: null,
    actively_at_work_condition_override: false,
    actively_at_work_condition: null,
    other_event_limits: null,
    overall_event_limit: null,
    sic_code: null,
    previous_insurer: null,
    previously_insured: "unknown",
    base_rate: null,
    optalitix_id: null,
  },
  schedule: {
    external_schedule_id: null,
    pension_scheme_tax_ref: null,
    effective_date: moment().add(1, "y").format("YYYY-MM-DD"),
    anniversary_date: moment().add(2, "y").format("YYYY-MM-DD"),
    automatic_acceptance_limit: null,
    created_by_id: null,
    created_at: "2023-04-17T16:40:03.214Z",
    modified_by_id: null,
    modified_at: "2023-04-17T16:40:55.126Z",
    document_key: null,
    payment_frequency: "M",
    data_upload_frequency: "A",
    policy_specific_condition_statements: null,
    policy_tcs_ref: "Test",
  },
  period: {
    number_of_lives: 99,
    period_start_date: moment().add(1, "y").format("YYYY-MM-DD"),
    period_end_date: moment().add(2, "y").format("YYYY-MM-DD"),
    annual_premium: 200000.0,
    period_premium: 200000.0,
    period_type: "initial",
  },
  invoice: {
    amount: 31780.0,
    date_issued: moment().format(format),
  },
  commissionTerm: {
    broker_commission: 0.02,
    yulife_commission: 0.02,
    negotiated_additional_commission: 0.0,
    true_up_date: "2023-04-17",
    effective_from: "2024-10-16",
    modified_by_id: null,
    created_by_id: null,
    modified_at: "2023-04-17T16:40:03.214Z",
    created_at: "2023-04-17T16:40:03.214Z",
  },
});

export const BUSINESS_PRODUCT_4_GHI = generateProductRecords({
  productCode: ProductCode.groupHealth,
  carrier: Carrier.Bupa,
  productId: "YUG1010666",
  policyName: "Justice League Policy GHI",
  businessAccountId: BUSINESS_ACCOUNT_4.data.business_account_id,
  startDate: moment().add(1, "y").format(format),
  product: {
    policy_start_date: moment().add(1, "week").format(format),
    eventStartDate: moment().add(1, "week").format("YYYY-MM-DD"),
    productGoalTag: GOAL_PRODUCTS_1.data.tag,
  },
  quote: {
    business_quote_id: "GOYT9B8HK4",
    external_quote_id: "1234",
    archived: false,
    unit_rate: null,
    provisional_automatic_acceptance_limit: null,
    provisional_yulife_commission: 0.02,
    provisional_negotiated_additional_commission: 0.0,
    provisional_broker_commission: 0.02,
    sum_assured: null,
    number_of_lives: 99,
    annual_premium: 50000.0,
    flex_benefit: true,
    base_earn_rate: 2,
    max_win_win_rebate: 0.0,
    quote_issued_date: moment().subtract(7, "d").format(),
    sales_person: "dfefsdf",
    provisional_payment_frequency: "M",
    provisional_data_upload_frequency: "A",
    deal_type: null,
    type_of_trust: null,
    created_by_id: null,
    created_at: "2023-04-17T16:40:03.214Z",
    modified_by_id: null,
    modified_at: "2023-04-17T16:40:55.126Z",
    technical_guide: null,
    actively_at_work_condition_override: false,
    actively_at_work_condition: null,
    other_event_limits: null,
    overall_event_limit: null,
    sic_code: null,
    previous_insurer: null,
    previously_insured: "unknown",
    base_rate: null,
    optalitix_id: null,
  },
  schedule: {
    business_quote_id: "GOYT9B8HK4",
    external_schedule_id: null,
    pension_scheme_tax_ref: null,
    effective_date: moment().format("YYYY-MM-DD"),
    anniversary_date: moment().add(1, "y").format("YYYY-MM-DD"),
    automatic_acceptance_limit: null,
    policy_tcs_ref: null,
    created_by_id: null,
    created_at: "2023-04-17T16:40:03.214Z",
    modified_by_id: null,
    modified_at: "2023-04-17T16:40:55.126Z",
    document_key: null,
    payment_frequency: "M",
    data_upload_frequency: "A",
    policy_specific_condition_statements: null,
  },
  period: {
    number_of_lives: 99,
    period_start_date: moment().add(1, "y").format("YYYY-MM-DD"),
    period_end_date: moment().add(2, "y").format("YYYY-MM-DD"),
    annual_premium: 200000.0,
    period_premium: 200000.0,
  },
  invoice: {
    amount: 31780.0,
    date_issued: moment().subtract(1, "w").format(format),
  },
  commissionTerm: {
    broker_commission: 0.02,
    yulife_commission: 0.02,
    negotiated_additional_commission: 0.0,
    true_up_date: "2023-04-17",
    effective_from: "2024-10-16",
    modified_by_id: null,
    created_by_id: null,
    modified_at: "2023-04-17T16:40:03.214Z",
    created_at: "2023-04-17T16:40:03.214Z",
  },
});

export const BUSINESS_PRODUCT_2_RGL = generateProductRecords({
  productCode: ProductCode.GLA_UM,
  carrier: Carrier.MetLife,
  productId: "YUG0000100",
  policyName: "SparkLens GLA_UM",
  businessAccountId: BUSINESS_ACCOUNT_2.data.business_account_id,
  startDate: "2022-02-02T00:00:00Z",
});

export const BUSINESS_PRODUCT_2_GIP = generateProductRecords({
  productCode: ProductCode.GIP_UM,
  carrier: Carrier.MetLife,
  productId: "YUG0000101",
  policyName: "SparkLens GIP_UM",
  businessAccountId: BUSINESS_ACCOUNT_2.data.business_account_id,
  startDate: "2022-02-02T00:00:00Z",
});

export const BUSINESS_PRODUCT_12_REWARD_PASS = generateProductRecords({
  productCode: ProductCode.RewardPass,
  carrier: Carrier.YuLife,
  productId: "RewardPass-1",
  policyName: "Reward Pass Product",
  businessAccountId: BUSINESS_ACCOUNT_6.data.business_account_id,
  startDate: moment().subtract(1, "month").format(format),
  schedule: {
    rateExpiryDate: moment().add(5, "y").format(format),
  },
  categories: [
    {
      categoryId: "1",
      categoryName: "Reward Pass Test Product",
      categoryDescription: "Reward Pass Prod",
      versionId: 1,
      versionArchived: false,
      isClosed: false,
      earnRate: 0,
    },
  ],
});
