source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby '>= 2.7.7'

gem 'cocoapods', '>= 1.11.3'
gem 'cocoapods-bugsnag', "~> 2.3"
gem 'cocoapods-patch', '~> 1.0', '>= 1.0.2'
