import { Colours, Style } from "@styles";
import { IThemeScreens } from "../theme.types";
import { commonStyles, fullImageStyle, LINE_COLOR } from "./_util";

export const earth: { [key: number]: IThemeScreens } = {
  [0]: {
    dailyStepsScreen: {
      online: {
        backgroundImage: require("@assets/daily-screen/planets/earth/forest.webp"),
        style: { ...fullImageStyle, backgroundColor: Colours.earth.forestLight1 },
        isLottie: false,
        isFullScreen: true,
      },
      eventPanel: {
        fontColor: Colours.neutral.n900,
        borderColor: Colours.earth.forestBorder,
        backgroundColor: Colours.earth.forestBg,
      },
      hasWhiteGlow: false,
      isLight: false,
      streakType: "forest",
      topBarType: "default",
      textStyle: { color: Colours.neutral.n900 },
    },
    challengeListScreen: {
      backgroundImage: require("@assets/challenge-list/planets/earth/forest.webp"),
      style: { ...fullImageStyle, backgroundColor: Colours.earth.forestLight2 },
      tileBackgroundColour: Colours.earth.forestYellow,
      durationBackgroundColour: Colours.earth.forestDuration,
      topBarType: "default",
    },
    challengeSuccessScreen: {
      isFullScreen: true,
      isLottie: false,
      backgroundImage: require("@assets/challenge-success/planets/earth/forest.webp"),
      style: { ...fullImageStyle, backgroundColor: Colours.earth.forestLight2 },
      textStyle: { color: Colours.neutral.n900 },
      lineColour: LINE_COLOR,
    },
    challengeFailedScreen: {
      isFullScreen: false,
      isLottie: false,
      backgroundImage: require("@assets/challenge-success/planets/earth/forest.webp"),
      style: { ...fullImageStyle, backgroundColor: Colours.earth.forestLight2 },
      textStyle: { color: Colours.neutral.n900 },
      lineColour: Colours.neutral.n900,
    },
    offlineScreen: {
      isFullScreen: false,
      isLottie: false,
      textColour: Colours.darkGray,
      backgroundImage: require("@assets/offline-screen/planets/earth/forest.webp"),
      style: {
        ...commonStyles,
        backgroundColor: Colours.backgrounds.lightGray,
        height: Style.adjust(344),
      },
    },
  },
  [1]: {
    dailyStepsScreen: {
      online: {
        backgroundImage: require("@assets/daily-screen/planets/earth/ocean.webp"),
        style: { ...fullImageStyle, backgroundColor: Colours.earth.oceanDark1 },
        isLottie: false,
        isFullScreen: true,
      },
      eventPanel: {
        fontColor: Colours.neutral.white,
        borderColor: Colours.earth.oceanBlue1,
        backgroundColor: Colours.earth.oceanBlue2,
      },
      hasWhiteGlow: false,
      isLight: true,
      streakType: "ocean",
      topBarType: "white",
      textStyle: { color: Colours.neutral.white },
    },
    challengeListScreen: {
      backgroundImage: require("@assets/challenge-list/planets/earth/ocean.webp"),
      style: { ...fullImageStyle, backgroundColor: Colours.earth.oceanDark2 },
      tileBackgroundColour: Colours.earth.oceanTile,
      durationBackgroundColour: Colours.earth.oceanDuration,
      topBarType: "white",
    },
    challengeSuccessScreen: {
      isFullScreen: true,
      isLottie: false,
      backgroundImage: require("@assets/challenge-success/planets/earth/ocean.webp"),
      style: { ...fullImageStyle, backgroundColor: Colours.earth.oceanDark2 },
      textStyle: { color: Colours.neutral.white },
      lineColour: LINE_COLOR,
    },
    challengeFailedScreen: {
      isFullScreen: true,
      isLottie: false,
      backgroundImage: require("@assets/challenge-success/planets/earth/ocean.webp"),
      style: { ...fullImageStyle, backgroundColor: Colours.earth.oceanDark2 },
      textStyle: { color: Colours.darkestGray },
      lineColour: Colours.neutral.n900,
    },
    offlineScreen: {
      isFullScreen: false,
      isLottie: false,
      textColour: Colours.neutral.white,
      backgroundImage: require("@assets/offline-screen/planets/earth/ocean.webp"),
      style: {
        ...commonStyles,
        backgroundColor: Colours.backgrounds.mediumGray,
      },
    },
  },
  [2]: {
    dailyStepsScreen: {
      online: {
        backgroundImage: require("@assets/daily-screen/planets/earth/desert.webp"),
        style: { ...fullImageStyle, backgroundColor: Colours.earth.oceanLight1 },
        isLottie: false,
        isFullScreen: true,
      },
      eventPanel: {
        fontColor: Colours.neutral.n900,
        borderColor: Colours.earth.oceanYellow,
        backgroundColor: Colours.earth.oceanYellowBg,
      },
      hasWhiteGlow: true,
      isLight: false,
      streakType: "desert",
      topBarType: "default",
      textStyle: { color: Colours.neutral.n900 },
    },
    challengeListScreen: {
      backgroundImage: require("@assets/challenge-list/planets/earth/desert.webp"),
      style: { ...fullImageStyle, backgroundColor: Colours.earth.oceanLight2 },
      tileBackgroundColour: Colours.earth.oceanTileAlpha,
      durationBackgroundColour: Colours.earth.oceanDurationLight,
      topBarType: "desert",
    },
    challengeSuccessScreen: {
      isFullScreen: true,
      isLottie: false,
      backgroundImage: require("@assets/challenge-success/planets/earth/desert.webp"),
      style: { ...fullImageStyle, backgroundColor: Colours.earth.oceanLight2 },
      textStyle: { color: Colours.neutral.n900 },
      lineColour: LINE_COLOR,
    },
    challengeFailedScreen: {
      isFullScreen: true,
      isLottie: false,
      backgroundImage: require("@assets/challenge-success/planets/earth/desert.webp"),
      style: { ...fullImageStyle, backgroundColor: Colours.earth.oceanLight2 },
      textStyle: { color: Colours.neutral.n900 },
      lineColour: Colours.neutral.n900,
    },
    offlineScreen: {
      isFullScreen: false,
      isLottie: false,
      textColour: Colours.darkGray,
      backgroundImage: require("@assets/offline-screen/planets/earth/desert.webp"),
      style: {
        ...commonStyles,
        backgroundColor: "Colours.backgrounds.lightGray",
      },
    },
  },
  [3]: {
    dailyStepsScreen: {
      online: {
        backgroundImage: require("@assets/daily-screen/planets/earth/mountain.webp"),
        style: { ...fullImageStyle, backgroundColor: Colours.earth.oceanLight3 },
        isLottie: false,
        isFullScreen: true,
      },
      eventPanel: {
        fontColor: Colours.neutral.n900,
        borderColor: Colours.earth.desertBorder,
        backgroundColor: Colours.earth.desertBg,
      },
      hasWhiteGlow: true,
      isLight: false,
      streakType: "mountain",
      topBarType: "default",
      textStyle: { color: Colours.neutral.n900 },
    },
    challengeListScreen: {
      backgroundImage: require("@assets/challenge-list/planets/earth/mountain.webp"),
      style: { ...fullImageStyle, backgroundColor: Colours.earth.oceanLight3 },
      tileBackgroundColour: Colours.earth.oceanTileFade,
      durationBackgroundColour: Colours.earth.oceanDurationFade,
      topBarType: "mountain",
    },
    challengeSuccessScreen: {
      isFullScreen: true,
      isLottie: false,
      backgroundImage: require("@assets/challenge-success/planets/earth/mountain.webp"),
      style: { ...fullImageStyle, backgroundColor: Colours.earth.oceanLight3 },
      textStyle: { color: Colours.neutral.n900 },
      lineColour: LINE_COLOR,
    },
    challengeFailedScreen: {
      isFullScreen: true,
      isLottie: false,
      backgroundImage: require("@assets/challenge-success/planets/earth/mountain.webp"),
      style: { ...fullImageStyle, backgroundColor: Colours.earth.oceanLight3 },
      textStyle: { color: Colours.neutral.n900 },
      lineColour: Colours.neutral.n900,
    },
    offlineScreen: {
      isFullScreen: false,
      isLottie: false,
      textColour: Colours.darkGray,
      backgroundImage: require("@assets/offline-screen/planets/earth/mountain.webp"),
      style: {
        ...commonStyles,
        backgroundColor: "Colours.backgrounds.lightGray",
      },
    },
  },
};
