fragment MaximiseYuSectionContentProgress on MaximiseYuSectionContentProgress {
  title
  current
  max
}

fragment MaximiseYuSectionContentBadge on MaximiseYuSectionContentBadge {
  label
  wrapperStyles {
    ...SduiStyle
  }
  textColor
}

fragment MaximiseYuSectionContentScrollItem on MaximiseYuSectionContentScrollItem {
  id
  image {
    ...RemoteImage
  }
  markdown
  onPress {
    ...SduiAction
  }
  done
  markdownStyleOverrides
}

fragment MaximiseYuSectionContentChallengeAmount on MaximiseYuSectionContentChallengeAmount {
  max
  left
}

fragment MaximiseYuSectionContent on MaximiseYuSectionContent {
  challengeAmount {
    ...MaximiseYuSectionContentChallengeAmount
  }
  scrollItems {
    ...MaximiseYuSectionContentScrollItem
  }
  badge {
    ...MaximiseYuSectionContentBadge
  }
  progress {
    ...MaximiseYuSectionContentProgress
  }
}

fragment MaximiseYuSection on MaximiseYuSection {
  id
  sectionInstanceId
  ready
  updateOnView
  loadingGroup
  content {
    ...MaximiseYuSectionContent
  }
}
