query GetReferralInformation(
  $limit: Int
  $offset: Int
  $businessAccountId: String!
  $hasSelectedBusinessAccount: Boolean!
) {
  referralInformation(limit: $limit, offset: $offset, businessAccountId: $businessAccountId)
    @include(if: $hasSelectedBusinessAccount) {
    rewardForReferral
    referralCode
    shareReferralCodeMessage
    background {
      id
      uri
    }
    codeDisclaimer
    shareButton
    markdown {
      headerTitle
      headerSubtitle
      shareBoxTitle
      historyTitle
      codeHistoryEmptyMessage
    }
    businessAccountId
  }
  theme: getMobileGameThemeForEmployment(businessAccountId: $businessAccountId)
    @include(if: $hasSelectedBusinessAccount) {
    ...MobileGameTheme
  }
}
