query GetReferralInformation(
  $limit: Int
  $offset: Int
  $businessAccountId: String
  $hasSelectedBusinessAccount: Boolean!
) {
  referralInformation(limit: $limit, offset: $offset, businessAccountId: $businessAccountId)
    @include(if: $hasSelectedBusinessAccount) {
    rewardForReferral
    referralLink
    background {
      id
      uri
    }
    shareCTA
    shareMessage
    disclaimer
    markdown {
      headerTitle
      headerSubtitle
      shareTitle
      historyTitle
      historyEmptyMessage
    }
    businessAccountId
  }
  activeEmployments: getActiveEmployments {
    id
    businessAccountId
    businessAccountName
  }
}
