query GetYuScreenProductList {
  getYuScreenProductList {
    heading
    body {
      id
      backgroundColor
      button {
        label
        onPress {
          productAction {
            productId
            nextRouteId
            nextModalId
            shouldBeNormalised
          }
          sduiAction {
            type
            payload
          }
        }
        event {
          type
          payload
        }
      }
      contentContainerStyles {
        property
        value
      }
      descriptionMarkdown
      descriptionMarkdownStyles {
        property
        value
      }
      images {
        image {
          id
          uri
        }
        width
      }
      titleMarkdown
      titleMarkdownStyles {
        property
        value
      }
      variant
    }
  }
}
