fragment YuScreenPopover on YuScreenPopover {
  id
  message
}

fragment YuScreenProductSlotItem on YuScreenProductSlotItem {
  itemUrl
  status
  earnRate
  productId
  coverType
  icon {
    name
    backgroundUrl
    colour
  }
  badge {
    badgeUrl
    text {
      value
      colour
    }
  }
  popover {
    ...YuScreenPopover
  }
}

fragment YuScreenProductSlot on YuScreenProductSlot {
  slot1 {
    ...YuScreenProductSlotItem
  }
  slot2 {
    ...YuScreenProductSlotItem
  }
  slot3 {
    ...YuScreenProductSlotItem
  }
  slot4 {
    ...YuScreenProductSlotItem
  }
}

fragment YuAvatarPart on AvatarPart {
  partId
  elements {
    name
    attributes {
      name
      value
    }
  }
}

fragment YuAvatarColor on AvatarColor {
  colorSchemeId
  colorScheme {
    main
    shadow
    light
    base
    eyebrows
    leftEar
    rightEar
    lips
    tongue
    nose
  }
}

fragment YuAvatar on UserAvatar {
  id
  hair {
    part {
      ...YuAvatarPart
    }
    color {
      ...YuAvatarColor
    }
  }
  facialHair {
    part {
      ...YuAvatarPart
    }
    color {
      ...YuAvatarColor
    }
  }
  head {
    part {
      ...YuAvatarPart
    }
    color {
      ...YuAvatarColor
    }
  }
  eyes {
    part {
      ...YuAvatarPart
    }
    color {
      ...YuAvatarColor
    }
  }
  body {
    part {
      ...YuAvatarPart
    }
    color {
      ...YuAvatarColor
    }
  }
  pants {
    part {
      ...YuAvatarPart
    }
    color {
      ...YuAvatarColor
    }
  }
  chest {
    part {
      ...YuAvatarPart
    }
    color {
      ...YuAvatarColor
    }
  }
  gloves {
    part {
      ...YuAvatarPart
    }
    color {
      ...YuAvatarColor
    }
  }
  boots {
    part {
      ...YuAvatarPart
    }
    color {
      ...YuAvatarColor
    }
  }
  headwear {
    part {
      ...YuAvatarPart
    }
    color {
      ...YuAvatarColor
    }
  }
  glasses {
    part {
      ...YuAvatarPart
    }
    color {
      ...YuAvatarColor
    }
  }
  makeup {
    part {
      ...YuAvatarPart
    }
    color {
      ...YuAvatarColor
    }
  }
}

fragment ProductPaymentHistoryInfoPanelButton on ProductPaymentHistoryInfoPanelButton {
  label
  onPress {
    ...SduiAction
  }
  event {
    ...SduiAction
  }
}

fragment ProductPaymentHistoryInfoPanelContainerActions on ProductPaymentHistoryInfoPanelContainerActions {
  onPress {
    ...SduiAction
  }
  event {
    ...SduiAction
  }
}

fragment YuScreenProductPaymentHistoryInfoPanel on YuScreenProductPaymentHistoryInfoPanel {
  markdown
  remoteImage {
    ...RemoteImage
  }
  type
  titleMarkdown
  showCloseIcon
  button {
    ...ProductPaymentHistoryInfoPanelButton
  }
  containerActions {
    ...ProductPaymentHistoryInfoPanelContainerActions
  }
}

fragment YuScreenProductPaymentHistoryItem on YuScreenProductPaymentHistoryItem {
  id
  amount
  date
  status
}

fragment YuScreenProductButtonAction on YuScreenProductButtonAction {
  productAction {
    ...ProductAction
  }
  sduiAction {
    ...SduiAction
  }
}

fragment YuScreenCarouselItem on YuScreenCarouselItem {
  backgroundColor
  button {
    label
    onPress {
      ...YuScreenProductButtonAction
    }
    event {
      ...SduiAction
    }
  }
  contentContainerStyles {
    ...SduiStyle
  }
  descriptionMarkdown
  descriptionMarkdownStyles {
    ...SduiStyle
  }
  images {
    ...VariableRemoteImage
  }
  titleMarkdown
  titleMarkdownStyles {
    ...SduiStyle
  }
  variant
}

fragment ProductCardCarouselSection on ProductCardCarouselSection {
  __typename
  id
  ready
  updateOnView
  content {
    title
    items {
      illustrations {
        square {
          ...RemoteImage
        }
        tall {
          ...RemoteImage
        }
        wide {
          ...RemoteImage
        }
      }
      logo {
        ...RemoteImage
      }
      productName
      title
      body
      label
      primaryCta
      onPrimaryPress {
        ...SduiAction
      }
      secondaryCta
      onSecondaryPress {
        ...SduiAction
      }
    }
    cta
    onPress {
      ...SduiAction
    }
  }
}

fragment WellbeingHubSection on WellbeingHubSection {
  __typename
  id
  ready
  updateOnView
  content {
    title
    items {
      id
      image {
        ...RemoteImage
      }
      title
      description
      route
    }
    buttonLabel
  }
}

fragment ReferralSection on ReferralSection {
  __typename
  id
  ready
  updateOnView
  content {
    illustration {
      ...VariableRemoteImage
    }
    title
    markdown
    buttonLabel
    buttonIcon {
      ...RemoteImage
    }
  }
}

fragment MaximiseYuSectionContentProgress on MaximiseYuSectionContentProgress {
  title
  current
  max
}

fragment MaximiseYuSectionContentBadge on MaximiseYuSectionContentBadge {
  label
  wrapperStyles {
    ...SduiStyle
  }
  textColor
}

fragment MaximiseYuSectionContentScrollItem on MaximiseYuSectionContentScrollItem {
  yuCoinAmount
  target
  type
  done
}

fragment MaximiseYuSectionContentChallengeAmount on MaximiseYuSectionContentChallengeAmount {
  max
  left
}

fragment MaximiseYuSectionContent on MaximiseYuSectionContent {
  challengeAmount {
    ...MaximiseYuSectionContentChallengeAmount
  }
  scrollItems {
    ...MaximiseYuSectionContentScrollItem
  }
  badge {
    ...MaximiseYuSectionContentBadge
  }
  progress {
    ...MaximiseYuSectionContentProgress
  }
}

fragment MaximiseYuSection on MaximiseYuSection {
  id
  ready
  updateOnView
  content {
    ...MaximiseYuSectionContent
  }
}

fragment YuScreenSection on YuScreenSection {
  __typename
  ... on SduiSection {
    ...SduiSection
  }
  ... on ProductCardCarouselSection {
    ...ProductCardCarouselSection
  }
  ... on WellbeingHubSection {
    ...WellbeingHubSection
  }
  ... on ReferralSection {
    ...ReferralSection
  }
  ... on MaximiseYuSection {
    ...MaximiseYuSection
  }
}
