query GetPendingUserFeedback($supportedTypes: [FeedbackFormQuestionType]) {
  journey: pendingMobileUserJourney {
    __typename
    journeyId
    delay
  }
  appStore: pendingAppStoreReview {
    __typename
    id
    image
    title
    body
    rejectedTitle
    rejectedBody
    showAfterEvent
    showAfterSeconds
  }
  form: pendingFeedbackForm(supportedTypes: $supportedTypes) {
    __typename
    id
    title
    label
    awardYucoin
    questions {
      __typename
      key
      questionText
      description
      image {
        id
        uri
      }
      icon {
        id
        uri
      }
      type
      isRoot
      range {
        __typename
        id
        min
        max
      }
      labels {
        __typename
        id
        left
        right
        placeholder
        submit
      }
      nextConditions {
        __typename
        id
        questionKey
        regexMatch
      }
      options {
        id
        label
        value
      }
    }
  }
}
