import { Carrier, ProductCode, generateProductRecords } from "@yu-life/yulife-bdd-framework";
import moment from "moment";
import {
    BUSINESS_ACCOUNT_10_GHI_REWARDS,
    BUSINESS_ACCOUNT_11_MPP,
    BUSINESS_ACCOUNT_GHI_8,
    BUSINESS_ACCOUNT_13_GHI_REWARDS,
} from "./business";
import { GOAL_PRODUCTS_1, GOAL_PRODUCTS_2, GOAL_PRODUCTS_3, GOAL_PRODUCTS_4 } from "../mongo/goal_products";

const format = "YYYY-MM-DDTHH:mm:ssZ";

export const BUSINESS_PRODUCT_8_GHI = generateProductRecords({
    productCode: ProductCode.groupHealth,
    carrier: Carrier.Bupa,
    productId: "YUG1010102",
    policyName: "BLYTHSWOOD Policy GHI",
    businessAccountId: BUSINESS_ACCOUNT_GHI_8.data.business_account_id,
    startDate: moment().add(1, "y").format(format),
    product: {
        policy_start_date: moment().add(1, "y").format(format),
        productGoalTag: GOAL_PRODUCTS_1.data.tag,
    },
    quote: {
        business_quote_id: "GOYT9B8HK3",
        external_quote_id: "1234",
        archived: false,
        unit_rate: null,
        provisional_automatic_acceptance_limit: null,
        provisional_yulife_commission: 0.02,
        provisional_negotiated_additional_commission: 0.0,
        provisional_broker_commission: 0.02,
        sum_assured: null,
        number_of_lives: 99,
        annual_premium: 50000.0,
        flex_benefit: true,
        base_earn_rate: 2,
        max_win_win_rebate: 0.0,
        quote_issued_date: moment().subtract(7, "d").format(),
        sales_person: "dfefsdf",
        provisional_payment_frequency: "M",
        provisional_data_upload_frequency: "A",
        deal_type: null,
        type_of_trust: null,
        created_by_id: null,
        created_at: "2023-04-17T16:40:03.214Z",
        modified_by_id: null,
        modified_at: "2023-04-17T16:40:55.126Z",
        technical_guide: null,
        actively_at_work_condition_override: false,
        actively_at_work_condition: null,
        other_event_limits: null,
        overall_event_limit: null,
        sic_code: null,
        previous_insurer: null,
        previously_insured: "unknown",
        base_rate: null,
        optalitix_id: null,
    },
    schedule: {
        business_quote_id: "GOYT9B8HK3",
        external_schedule_id: null,
        pension_scheme_tax_ref: null,
        effective_date: moment().add(1, "y").format("YYYY-MM-DD"),
        anniversary_date: moment().add(11, "m").format("YYYY-MM-DD"),
        automatic_acceptance_limit: null,
        policy_tcs_ref: null,
        created_by_id: null,
        created_at: "2023-04-17T16:40:03.214Z",
        modified_by_id: null,
        modified_at: "2023-04-17T16:40:55.126Z",
        document_key: null,
        payment_frequency: "M",
        data_upload_frequency: "A",
        policy_specific_condition_statements: null,
    },
    period: {
        number_of_lives: 99,
        period_start_date: moment().add(1, "y").format("YYYY-MM-DD"),
        period_end_date: moment().add(2, "y").format("YYYY-MM-DD"),
        annual_premium: 200000.0,
        period_premium: 200000.0,
    },
    invoice: {
        amount: 31780.0,
        date_issued: moment().subtract(1, "w").format(format),
    },
    commissionTerm: {
        broker_commission: 0.02,
        yulife_commission: 0.02,
        negotiated_additional_commission: 0.0,
        true_up_date: "2023-04-17",
        effective_from: "2024-10-16",
        modified_by_id: null,
        created_by_id: null,
        modified_at: "2023-04-17T16:40:03.214Z",
        created_at: "2023-04-17T16:40:03.214Z",
    },
});

export const BUSINESS_PRODUCT_13_GHI_REWARDS = generateProductRecords({
    productCode: ProductCode.groupHealth,
    carrier: Carrier.Bupa,
    productId: "YUG1010107",
    policyName: "BLYTHSWOOD Policy GHI",
    businessAccountId: BUSINESS_ACCOUNT_10_GHI_REWARDS.data.business_account_id,
    startDate: "2020-02-02",
    product: {
        policy_start_date: "2020-02-02T00:00:00Z",
        eventStartDate: moment().subtract(1, "d").format("YYYY-MM-DD"),
        productGoalTag: GOAL_PRODUCTS_1.data.tag,
    },
    quote: {
        business_quote_id: "GOYT9B8HK4",
        external_quote_id: "1234",
        archived: false,
        unit_rate: null,
        provisional_automatic_acceptance_limit: null,
        provisional_yulife_commission: 0.02,
        provisional_negotiated_additional_commission: 0.0,
        provisional_broker_commission: 0.02,
        sum_assured: null,
        number_of_lives: 99,
        annual_premium: 50000.0,
        flex_benefit: true,
        base_earn_rate: 2,
        max_win_win_rebate: 0.0,
        quote_issued_date: "2020-02-02T00:00:00Z",
        sales_person: "dfefsdf",
        provisional_payment_frequency: "M",
        provisional_data_upload_frequency: "A",
        deal_type: null,
        type_of_trust: null,
        created_by_id: null,
        created_at: "2020-02-02T00:00:00Z",
        modified_by_id: null,
        modified_at: "2023-04-17T16:40:55.126Z",
        technical_guide: null,
        actively_at_work_condition_override: false,
        actively_at_work_condition: null,
        other_event_limits: null,
        overall_event_limit: null,
        sic_code: null,
        previous_insurer: null,
        previously_insured: "unknown",
        base_rate: null,
        optalitix_id: null,
    },
    schedule: {
        business_quote_id: "GOYT9B8HK3",
        external_schedule_id: null,
        pension_scheme_tax_ref: null,
        effective_date: "2020-02-02",
        anniversary_date: "2020-02-02",
        automatic_acceptance_limit: null,
        policy_tcs_ref: null,
        created_by_id: null,
        created_at: "2020-02-02T00:00:00Z",
        modified_by_id: null,
        modified_at: "2023-04-17T16:40:55.126Z",
        document_key: null,
        payment_frequency: "M",
        data_upload_frequency: "A",
        policy_specific_condition_statements: null,
    },
    period: {
        number_of_lives: 99,
        period_start_date: "2020-02-02T00:00:00Z",
        period_end_date: moment().add(1, "y").format("YYYY-MM-DD"),
        annual_premium: 200000.0,
        period_premium: 200000.0,
    },
    invoice: {
        amount: 31780.0,
        date_issued: moment().subtract(1, "w").format(format),
    },
    commissionTerm: {
        broker_commission: 0.02,
        yulife_commission: 0.02,
        negotiated_additional_commission: 0.0,
        true_up_date: "2023-04-17",
        effective_from: "2024-10-16",
        modified_by_id: null,
        created_by_id: null,
        modified_at: "2023-04-17T16:40:03.214Z",
        created_at: "2020-02-02T00:00:00Z",
    },
});

export const BUSINESS_PRODUCT_14_GHI = generateProductRecords({
    productCode: ProductCode.groupHealth,
    carrier: Carrier.Bupa,
    productId: "YUG1010110",
    policyName: "Biz 11 Policy GHI",
    businessAccountId: BUSINESS_ACCOUNT_11_MPP.data.business_account_id,
    startDate: moment().subtract(1, "year").format("YYYY-MM-DD"),
});

export const BUSINESS_PRODUCT_15_GHI_REWARDS = generateProductRecords({
    productCode: ProductCode.groupHealth,
    carrier: Carrier.Bupa,
    productId: "YUG1010113",
    policyName: "GHI Rewards 2",
    businessAccountId: BUSINESS_ACCOUNT_10_GHI_REWARDS.data.business_account_id,
    startDate: "2020-02-02",
    product: {
        policy_start_date: "2020-02-02T00:00:00Z",
        eventStartDate: moment().subtract(1, "d").format("YYYY-MM-DD"),
        productGoalTag: GOAL_PRODUCTS_2.data.tag,
    },
    quote: {
        business_quote_id: "GOYT9B8HK5",
        external_quote_id: "1234",
        archived: false,
        unit_rate: null,
        provisional_automatic_acceptance_limit: null,
        provisional_yulife_commission: 0.02,
        provisional_negotiated_additional_commission: 0.0,
        provisional_broker_commission: 0.02,
        sum_assured: null,
        number_of_lives: 99,
        annual_premium: 50000.0,
        flex_benefit: true,
        base_earn_rate: 2,
        max_win_win_rebate: 0.0,
        quote_issued_date: "2020-02-02T00:00:00Z",
        sales_person: "dfefsdf",
        provisional_payment_frequency: "M",
        provisional_data_upload_frequency: "A",
        deal_type: null,
        type_of_trust: null,
        created_by_id: null,
        created_at: "2020-02-02T00:00:00Z",
        modified_by_id: null,
        modified_at: "2023-04-17T16:40:55.126Z",
        technical_guide: null,
        actively_at_work_condition_override: false,
        actively_at_work_condition: null,
        other_event_limits: null,
        overall_event_limit: null,
        sic_code: null,
        previous_insurer: null,
        previously_insured: "unknown",
        base_rate: null,
        optalitix_id: null,
    },
    schedule: {
        business_quote_id: "GOYT9B8HK3",
        external_schedule_id: null,
        pension_scheme_tax_ref: null,
        effective_date: "2020-02-02",
        anniversary_date: "2020-02-02",
        automatic_acceptance_limit: null,
        policy_tcs_ref: null,
        created_by_id: null,
        created_at: "2020-02-02T00:00:00Z",
        modified_by_id: null,
        modified_at: "2023-04-17T16:40:55.126Z",
        document_key: null,
        payment_frequency: "M",
        data_upload_frequency: "A",
        policy_specific_condition_statements: null,
    },
    period: {
        number_of_lives: 99,
        period_start_date: "2020-02-02T00:00:00Z",
        period_end_date: moment().add(1, "y").format("YYYY-MM-DD"),
        annual_premium: 200000.0,
        period_premium: 200000.0,
    },
    invoice: {
        amount: 31780.0,
        date_issued: moment().subtract(1, "w").format(format),
    },
    commissionTerm: {
        broker_commission: 0.02,
        yulife_commission: 0.02,
        negotiated_additional_commission: 0.0,
        true_up_date: "2023-04-17",
        effective_from: "2024-10-16",
        modified_by_id: null,
        created_by_id: null,
        modified_at: "2023-04-17T16:40:03.214Z",
        created_at: "2020-02-02T00:00:00Z",
    },
});

export const BUSINESS_PRODUCT_16_GHI_REWARDS = generateProductRecords({
    productCode: ProductCode.groupHealth,
    carrier: Carrier.Bupa,
    productId: "YUG1010114",
    policyName: "GHI Rewards 3",
    businessAccountId: BUSINESS_ACCOUNT_13_GHI_REWARDS.data.business_account_id,
    startDate: moment().subtract(1, "years").format("YYYY-MM-DD"),
    product: {
        policy_start_date: moment().subtract(1, "years").format("YYYY-MM-DD"),
        eventStartDate: moment().subtract(1, "years").format("YYYY-MM-DD"),
        productGoalTag: GOAL_PRODUCTS_3.data.tag,
    },
    quote: {
        business_quote_id: "GOYT9B8HK6",
        external_quote_id: "1234",
        archived: false,
        unit_rate: null,
        provisional_automatic_acceptance_limit: null,
        provisional_yulife_commission: 0.02,
        provisional_negotiated_additional_commission: 0.0,
        provisional_broker_commission: 0.02,
        sum_assured: null,
        number_of_lives: 99,
        annual_premium: 50000.0,
        flex_benefit: true,
        base_earn_rate: 2,
        max_win_win_rebate: 0.0,
        quote_issued_date: "2020-02-02T00:00:00Z",
        sales_person: "dfefsdf",
        provisional_payment_frequency: "M",
        provisional_data_upload_frequency: "A",
        deal_type: null,
        type_of_trust: null,
        created_by_id: null,
        created_at: "2020-02-02T00:00:00Z",
        modified_by_id: null,
        modified_at: "2023-04-17T16:40:55.126Z",
        technical_guide: null,
        actively_at_work_condition_override: false,
        actively_at_work_condition: null,
        other_event_limits: null,
        overall_event_limit: null,
        sic_code: null,
        previous_insurer: null,
        previously_insured: "unknown",
        base_rate: null,
        optalitix_id: null,
    },
    schedule: {
        business_quote_id: "GOYT9B8HK3",
        external_schedule_id: null,
        pension_scheme_tax_ref: null,
        effective_date: "2020-02-02",
        anniversary_date: "2020-02-02",
        automatic_acceptance_limit: null,
        policy_tcs_ref: null,
        created_by_id: null,
        created_at: "2020-02-02T00:00:00Z",
        modified_by_id: null,
        modified_at: "2023-04-17T16:40:55.126Z",
        document_key: null,
        payment_frequency: "M",
        data_upload_frequency: "A",
        policy_specific_condition_statements: null,
    },
    period: {
        number_of_lives: 99,
        period_start_date: moment().subtract(1, "years").format("YYYY-MM-DD"),
        period_end_date: moment().subtract(1, "days").format("YYYY-MM-DD"),
        annual_premium: 200000.0,
        period_premium: 200000.0,
    },
    invoice: {
        amount: 31780.0,
        date_issued: moment().subtract(1, "years").format("YYYY-MM-DD"),
    },
    commissionTerm: {
        broker_commission: 0.02,
        yulife_commission: 0.02,
        negotiated_additional_commission: 0.0,
        true_up_date: "2023-04-17",
        effective_from: "2024-10-16",
        modified_by_id: null,
        created_by_id: null,
        modified_at: "2023-04-17T16:40:03.214Z",
        created_at: "2020-02-02T00:00:00Z",
    },
});

export const BUSINESS_PRODUCT_17_METLIFE_GIP = generateProductRecords({
    productCode: ProductCode.GIP_UM,
    carrier: Carrier.MetLife,
    productId: "PROD_869",
    policyName: "Policy GIP Game",
    businessAccountId: BUSINESS_ACCOUNT_10_GHI_REWARDS.data.business_account_id,
    startDate: "2020-02-02",
    product: {
        policy_start_date: moment().subtract(1, "years").format("YYYY-MM-DD"),
        eventStartDate: moment().subtract(1, "years").format("YYYY-MM-DD"),
        productGoalTag: GOAL_PRODUCTS_4.data.tag,
    },
    quote: {
        number_of_lives: 10,
        valid_till: moment().add(1, "m").format(),
        flex_benefit: false,
        deal_type: "deal",
        type_of_trust: "own_trust",
        sales_person: "Isaac",
        max_win_win_rebate: 0.02,
        provisional_negotiated_additional_commission: 0.3,
        sum_assured: 100000.0,
        annual_premium: 20000.0,
        base_earn_rate: 10,
        quote_issued_date: "2021-09-03",
        provisional_payment_frequency: "A",
        provisional_broker_commission: 0.1,
        provisional_yulife_commission: 0.3,
        provisional_data_upload_frequency: "A",
        provisional_rate_expiry_date: "2025-06-02",
        provisional_anniversary_date: "2022-06-03",
        provisional_automatic_acceptance_limit: "200000",
        unit_rate: 1.1234,
        external_quote_id: 6000,
      },
    schedule: {
      effective_date: "2020-02-02",
      payment_frequency: "A",
      data_upload_frequency: "A",
      rate_expiry_date: "2020-02-02",
      anniversary_date: "2020-02-02",
      automatic_acceptance_limit: "100000",
      policy_tcs_ref: "Test",
    },
    period: {
        version_id: 1,
        number_of_lives: 10,
        period_start_date: "2021-06-03",
        period_end_date: "2022-06-02",
        sum_assured: 100000.0,
        annual_premium: 200000.0,
        period_premium: 200000.0,
      },
      invoice: {
        amount: 20000,
      },
  });