export const P2P_MESSAGES = [
  "Great work today! ⭐️",
  "You nailed it! 🎯",
  "Certified legend! 🏆",
  "Smashing it! 💥",
  "You got this! 💪",
  "Have a nice day! 😊",
  "Good morning! ☀️",
  "Here's a huge thank you! 🙏",
  "You = Awesome. Me = Grateful! 💫",
  "You're the best! ❤️",
  "Happy birthday! 🎂",
  "Congratulations! 🎉",
  "High five! 👏",
  "Here's a little sparkle to your day ✨",
  "Sending you energy! 🤗",
  "You're the GOAT! 🐐",
  "Boo-yah! 👊",
  "SLAY 💅",
];

export const P2P_GIFTING_AMOUNTS = [10, 25, 50, 100, 250];

export const P2P_GIFTING_STICKERS = [
  "gift",
  "gift-2",
  "gift-3",
  "trophy",
  "heart",
  "cake",
  "earthy",
  "arch",
  "surge",
  "letter",
  "deez-nuts",
  "squirrel",
  "rocket",
  "cookie",
  "snail",
  "rainbow",
  "lantern",
  "thumbs-up",
  "thug-yugi",
  "yugi-headphones",
  "fuji",
  "love-bird",
  "pumpkin",
  "blowhole",
  "party",
  "friends",
  "sleepy",
  "incognito-yugi",
  "helping",
  "joy",
  "heart-yugi",
  "magic",
];
