export interface PossibleTypesResultData {
  possibleTypes: {
    [key: string]: string[];
  };
}
const result: PossibleTypesResultData = {
  possibleTypes: {
    BulkMemberImportImportRow: [
      "BulkMemberImportInsertRow",
      "BulkMemberImportLeaverRow",
      "BulkMemberImportMissingRow",
      "BulkMemberImportNoOpRow",
      "BulkMemberImportSkippedRow",
      "BulkMemberImportUnknownRow",
      "BulkMemberImportUpdateRow",
    ],
    BusinessSurveyCampaignBase: ["BusinessSurveyCampaign", "BusinessSurveyCampaignSearchResultsEntry"],
    BusinessSurveyStep: ["StepMultipleChoice", "StepNps", "StepOpenAnswer", "StepScale"],
    ContentItem: [
      "ContentItemAccordion",
      "ContentItemAppDownloadPrompt",
      "ContentItemBeneficiariesSection",
      "ContentItemBlurredRaysWrapper",
      "ContentItemBox",
      "ContentItemBoxOptionCard",
      "ContentItemButton",
      "ContentItemChoice",
      "ContentItemCollapsingGenericHeader",
      "ContentItemComparisonTableSelectPackage",
      "ContentItemConfirm",
      "ContentItemDatePicker",
      "ContentItemDependants",
      "ContentItemDropdownInput",
      "ContentItemFade",
      "ContentItemForm",
      "ContentItemHeaderBar",
      "ContentItemHeroLayout",
      "ContentItemHint",
      "ContentItemImage",
      "ContentItemImageChoice",
      "ContentItemInfoCard",
      "ContentItemKeyValueBox",
      "ContentItemLinearGradient",
      "ContentItemLottie",
      "ContentItemMarkdown",
      "ContentItemMarkdownBlock",
      "ContentItemMedia",
      "ContentItemPad",
      "ContentItemPaymentButton",
      "ContentItemPerks",
      "ContentItemPerksComparison",
      "ContentItemPill",
      "ContentItemProcessingTimer",
      "ContentItemProductDetailsHeader",
      "ContentItemProductDetailsHoldingHeader",
      "ContentItemProgressBar",
      "ContentItemRadio",
      "ContentItemRewardsBanner",
      "ContentItemRowIconTextBanner",
      "ContentItemScale",
      "ContentItemSectionHeading",
      "ContentItemSelectScheme",
      "ContentItemSelectedPackageAccordion",
      "ContentItemSelectedPackageCard",
      "ContentItemSelectedPackageCards",
      "ContentItemSexPicker",
      "ContentItemShowHideBalance",
      "ContentItemSliderInput",
      "ContentItemStackedShadowWrapper",
      "ContentItemStages",
      "ContentItemSwitch",
      "ContentItemTable",
      "ContentItemText",
      "ContentItemTextAreaInput",
      "ContentItemTextGroup",
      "ContentItemTextInput",
      "ContentItemWrapper",
      "ContentItemYuCoinPower",
    ],
    ContentItemFormElements: ["ContentItemFormSelectInput", "ContentItemFormSubmitButton", "ContentItemFormTextInput"],
    ContentYuScreenProductItem: ["ContentItemLottie", "ContentItemText"],
    PaymentIntent: ["StripePaymentIntent"],
    TeamAnalyticsTableData: ["TeamAnalyticsTableDataFloat", "TeamAnalyticsTableDataString"],
    YuScreenProductDetailsContentItem: [
      "ContentItemAppDownloadPrompt",
      "ContentItemBeneficiariesSection",
      "ContentItemBoxOptionCard",
      "ContentItemButton",
      "ContentItemChoice",
      "ContentItemCollapsingGenericHeader",
      "ContentItemFade",
      "ContentItemHeaderBar",
      "ContentItemHint",
      "ContentItemImage",
      "ContentItemImageChoice",
      "ContentItemInfoCard",
      "ContentItemKeyValueBox",
      "ContentItemLinearGradient",
      "ContentItemMarkdown",
      "ContentItemPad",
      "ContentItemPerks",
      "ContentItemProcessingTimer",
      "ContentItemProductDetailsHeader",
      "ContentItemProductDetailsHoldingHeader",
      "ContentItemRewardsBanner",
      "ContentItemRowIconTextBanner",
      "ContentItemSelectedPackageCard",
      "ContentItemText",
      "ContentItemWrapper",
      "ContentItemYuCoinPower",
    ],
    YuScreenSection: [
      "FeatureCardSection",
      "HeroCardSection",
      "MaximiseYuSection",
      "ProductCardCarouselSection",
      "ReferralSection",
      "SduiSection",
      "SmokingSection",
      "WellbeingHubSection",
    ],
  },
};
export default result;
