query GetMobileRewardsGoalProductMilestones {
  getMobileRewardsGoalProductMilestones {
    goalProductMilestones {
      title
      backgroundImage {
        ...RemoteImage
      }
      challenges {
        icon {
          ...RemoteImage
        }
        description
      }
      progressBar {
        current
        max
      }
      milestones {
        value
        shouldAttractAttention
        rewardClaimed
      }
      fontColor
      backgroundColor
      borderColor
      tags {
        tag
        icon {
          ...RemoteImage
        }
      }
      sduiAction {
        ...SduiAction
      }
    }
    hint {
      ...ContentItemHint
    }
  }
}
