query GetMobileRewardsList($tag: String) {
  data: getMobileRewardsList(tag: $tag) {
    __typename
    id
    sduiStepId
    rewardStoreLocation
    rewardStoreLocationLabel
    hasUserSelectedStoreLocation
    rewardStoreAccessRevokesAt
    tags
    list {
      __typename
      id
      isLocked
      showLockedRewardOverlay
      name
      description
      imageUrl {
        ...RemoteImage
      }
      pills {
        __typename
        id
        text
        backgroundColor
      }
      teaseDetails {
        progress
        target
        rewardQuantity
        image {
          ...RemoteImage
        }
        overlayImage {
          ...RemoteImage
        }
        theme {
          primaryColor
          secondaryColor
          overlayColor
        }
        hint {
          label
          description
        }
        modalTitle
      }
    }
  }
}
