query GetMobileUnlockableBattlePassVouchers($passType: String) {
  getMobileUnlockableBattlePassVouchers(passType: $passType) {
    header {
      title
      heading
      description
      background {
        image {
          ...RemoteImage
        }
        color
        passBackground {
          backgroundImage {
            ...RemoteImage
          }
          foregroundImage {
            ...RemoteImage
          }
          color
          gradient {
            colors
            stops
            angle
          }
        }
      }
    }
    games {
      id
      title
      icon {
        ...RemoteImage
      }
      info {
        ...ContentItemWrapper
      }
      rewards {
        ...MobileGameBattlePassReward
      }
      progress {
        current
        max
        title
        info
      }
    }
    content {
      ...ContentItemWrapper
    }
    futureGames {
      id
      title
      description
      startDateCopy
      heroImage {
        ...RemoteImage
      }
    }
  }
}
