// TODO: If possible, generate type from server and download
// Should be GetCurrentUser_getCurrentUser_userFeatures["name"]

export const features = [
  "showActivity",
  "showTodayYucoin",
  "showNotifications",
  "showStreaks",
  "showCompletedLevel",
  "showCounter",
  "showBuildNumber",
  "showSettings",
  "showCreateLeaderboard",
  "showAdvancedLeaderboards",
  "disableUserEntries",
  "showConnections",
  "fitbit",
  "showLastSynced",
  "newPassiveValidationRule",
  "showWegiftPicker",
  "usePassiveMeditation",
  "showStats",
  "statsShowCoinGeneralTotalYearned",
  "statsShowCoinRecommendationCard",
  "statsShowCoinGeneralTotalRedeemedCard",
  "statsShowCoinAchievementCard",
  "statsShowChallengeGeneralCard",
  "statsShowChallengeRecommendationCard",
  "statsShowChallengeComparisonCard",
  "statsShowStepsRecommendationCard",
  "statsShowStepsGeneralCard",
  "statsShowStepsBestScoreCard",
  "statsShowStepsGraphCard",
  "statsShowMindfulnessRecommendationCard",
  "statsShowMindfulnessGeneralCard",
  "statsShowMindfulnessBestScoreCard",
  "statsShowMindfulnessGraphCard",
  "statsShowCyclingRecommendationCard",
  "statsShowCyclingGeneralCard",
  "statsShowCyclingBestScoreCard",
  "statsShowCyclingGraphCard",
  "familyIncomeBenefits",
  "hideYuMatterScreen",
  "hideSmartHealthScreen",
  "hideFeedbackModals",
  "showDuels",
];
