// TODO: If possible, generate type from server and download
// Should be GetCurrentUser_getCurrentUser_userFeatures["name"]

export const features = [
  "showNotifications",
  "showStreaks",
  "disableUserEntries",
  "showConnections",
  "gameSettingsLeaderboardsVisible",
  "fitbit",
  "newPassiveValidationRule",
  "hideYuMatterScreen",
  "hideSmartHealthScreen",
  "hideFeedbackModals",
  "showDuels",
  "yuScreenV3",
  "limitPedometerSteps",
  "showReferrals",
  "tempAppMenuNewReferralOption",
  "showBuffs",
  "useActiveChallengesService",
  "waitForStepsSync",
  "limitStepsLastUpdateEnabled",
  "enableBikingHand",
  "enableBikingMountain",
  "enableBikingRoad",
  "enableBikingSpinning",
  "enableBikingStationary",
  "enableBikingUtility",
  "enableDebugTool",
  "loggingEnabled",
  "logYuniversity",
  "showYuniversityMenuLink",
  "retryChallengeResultQuery",
  "showAllLanguages",
  "enableResumeInAppMeditation",
  "canFallbackToStepDetectorSensor",
  "enablePopToRootOnDateChange",
  "tempEnableClientAjvValidation",
  "tempGameUseSettingsConfigForQuestMap",
  "tempEnableYuScreenV5",
];
