mutation SubmitMobileQuestLevelSudokuSolution($results: MobileQuestSudokuSubmission!) {
  submitMobileQuestLevelSudokuSolution(results: $results) {
    level
    startDateTime
    status
    endDateTime
    incomingData {
      steps
      meditation
      distance
      duration
      calories
    }
    milestoneLog {
      data {
        steps
        meditation
        distance
        duration
        calories
      }
    }
    yuCoinAwarded
    rating
    completionSummary {
      ...ChallengeCompletionSummary
    }
  }
}
