mutation CreateMobileQuestLevelChallenge(
  $level: Int!
  $levelSlotTemplateId: String!
  $yuniversalMap: Int
  $contentId: String
  $createdBySource: ActiveChallengeSourceType
) {
  createMobileQuestLevelChallenge(
    level: $level
    levelSlotTemplateId: $levelSlotTemplateId
    yuniversalMap: $yuniversalMap
    contentId: $contentId
    createdBySource: $createdBySource
  ) {
    additionalChallengePeriodDisabled
    challengeDataQueryRetryLimit
    hideExternalLinks
    challenge {
      id
      level
      yuniversalMap
      levelSlotTemplateId
      status
      startDateTime
      endDateTime
    }
    levelSlot {
      subtype
      unit
      shouldEndOnLastGoalAchieved
      fitKitTypes
      yuHealth {
        ...YuHealthOptions
      }
      milestones {
        id
        XP
        coins
        target {
          steps
          meditation
          distance
          duration
          calories
        }
      }
    }
    nextLevelAvailableAt
    chest {
      type
      value
    }
    yuniversalChest {
      chestType
      title
      items {
        icon {
          id
          uri(options: { width: 180, height: 180 })
        }
        description
        backgroundColour
        shadowColour
        textColour
        starColour
        tooltip {
          title
          description
          cta
        }
      }
    }
  }
}
