query GetMobileQuestLevelChallengeDetails($level: Int!, $yuniversalMap: Int, $levelSlotTemplateId: String!) {
  getMobileQuestLevelChallengeDetails(
    level: $level
    yuniversalMap: $yuniversalMap
    levelSlotTemplateId: $levelSlotTemplateId
  ) {
    id
    heading
    backgroundColour
    progressBar {
      name
      barColor
      goalTextColor
      progressColor
      progressGoalEmpty
      progressGoalFilled
      progressStarEmpty
      progressStarFilled
      progressTextColor
    }
    assets {
      backgroundImage {
        id
        uri
      }
      detailsImage {
        id
        uri
      }
      tileImage {
        id
        uri
      }
      historyImage {
        id
        uri
      }
    }
    topBarType
    actionStyles {
      primaryColour
      secondaryColour
    }
  }
}
