export default {
  bighornSheep: require("../../../../../assets/challenge-tile/bighornSheep.png"),
  bird: require("../../../../../assets/challenge-tile/bird.png"),
  camel: require("../../../../../assets/challenge-tile/camel.png"),
  desertFox: require("../../../../../assets/challenge-tile/desertFox.png"),
  dolphin: require("../../../../../assets/challenge-tile/dolphin.png"),
  snail: require("../../../../../assets/challenge-tile/snail.png"),
  lock: require("../../../../../assets/icons/lock.png"),
  meerkat: require("../../../../../assets/challenge-tile/meerkat.png"),
  next: require("../../../../../assets/icons/next.png"),
  rabbit: require("../../../../../assets/challenge-tile/rabbit.png"),
  otter: require("../../../../../assets/challenge-tile/otter.png"),
  squirrel: require("../../../../../assets/challenge-tile/squirrel.png"),
  tortoise: require("../../../../../assets/challenge-tile/tortoise.png"),
  whale: require("../../../../../assets/challenge-tile/whale.png"),
  deer: require("../../../../../assets/challenge-tile/deer.png"),
  owl: require("../../../../../assets/challenge-tile/owl.png"),
  whiteBighornSheep: require("../../../../../assets/challenge-tile/whiteBighornSheep.png"),
  wolf: require("../../../../../assets/challenge-tile/wolf.png"),
  hedgehog: require("../../../../../assets/challenge-tile/hedgehog.png"),
  chameleon: require("../../../../../assets/challenge-tile/chameleon.png"),
  bear: require("../../../../../assets/challenge-tile/bear.png"),
  hedgehogFish: require("../../../../../assets/challenge-tile/hedgehogFish.png"),
};
