fragment ContentItemBoxOptionCard on ContentItemBoxOptionCard {
  id
  contentItemBoxOptionCardTitle: title
  contentItemBoxOptionCardDescription: description
  contentItemBoxOptionCardDescriptionTextType: descriptionTextType
  image {
    ...RemoteImage
  }
  onPress {
    ...SduiAction
  }
  event {
    ...SduiAction
  }
  styles {
    ...SduiStyle
  }
  innerHeight
  subtitle
  subtitleTextType
  titleWrapperStyles {
    ...SduiStyle
  }
  subtitleWrapperStyles {
    ...SduiStyle
  }
  descriptionNumberOfLines
  titleNumberOfLines
}
