fragment ContentItemScrollableItemsPicker on ContentItemScrollableItemsPicker {
  id
  answerKey
  styles {
    ...SduiStyle
  }
  range {
    min
    max
    step
  }
  coverMap {
    coverType
    max
  }
  styleVariants {
    id
    minVisibleIndex
    maxVisibleIndex
    item {
      color
    }
    overlay {
      backdropStyles {
        ...SduiStyle
      }
      highlightLabel
      highlightLabelColor
      overlayTitle
      overlayTitleWrapperStyles {
        ...SduiStyle
      }
    }
  }
}
