query GetStreakDetails {
  getStreakDetails {
    teaserTitle
    hint {
      label
      description
      image {
        id
        uri
      }
      onPress {
        type
        payload
      }
    }
    goalMilestone {
      rewardTitle
      progress
      target
      rewardQuantity
      showSparks
      image {
        id
        uri
      }
      overlayImage {
        ...RemoteImage
      }
      theme {
        primaryColor
        secondaryColor
        overlayColor
      }
    }
  }
}
