query GetUserProfile {
  getUserProfile {
    supportConfig {
      supportLevel
    }
    gameSettings {
      cyclingMeasurement
      maxStepsAnomalyWindowMs
      blackListedNavBarTabs
      blackListApps {
        steps
      }
      rewards {
        hasVoucherStore
        hasDonationBattlepass
        hasUnlockableBattlepassVouchers
      }
      debugToolsEnabled
      debugQueriesToolEnabled
    }
    surge {
      endDateTime
      multiplier
      title
      description
      lottie {
        ...ContentItemLottie
      }
    }
    earnRate
    avatar {
      isAvatarCreated
      avatarRemoteFiles {
        svgFull: image(options: { format: svg })
        pngFull: image
        pngMini: image(options: { width: 66.25, height: 138.25 })
      }
    }
    passiveChallengesLastUpdate {
      cycling
      meditation
      steps
    }
    passiveHourlyActivityLastUpdate {
      steps
    }
    endPointsVersion {
      getMobileCopy
      getMobileAssets
    }
    notification {
      ...UserProfileNotification
    }
    badgeCounts {
      ...UserProfileBadgeCounts
    }
    heroCards {
      ...HeroCard
    }
    events {
      ...UserProfileEvents
    }
    supportConfig {
      supportLevel
    }
    todayScreen {
      ...UserProfileTodayScreen
    }
  }
}
