query GetPersonalProductStepDetachedDocuments($productId: String!) {
  getPersonalProductStepDetachedDocuments(productId: $productId) {
    stepId
    customerProductId
    body {
      __typename
      ... on ContentItemPersonalProductDocuments {
        id
        headingImage {
          id
          image {
            id
            uri
          }
        }
        headingMarkdown {
          id
          markdown
          parsedMarkdown
        }
        documents {
          id
          linkLabel
          rightIcon {
            id
            uri
          }
          leftIcon {
            id
            uri
          }
          url
        }
      }
    }
  }
}
