query GetPersonalProductStep($productId: String!) {
  getPersonalProductStep(productId: $productId) {
    stepId
    customerProductId
    stepData
    containerStyles {
      ...SduiStyle
    }
    footerStyles {
      ...SduiStyle
    }
    body {
      __typename
      ... on ContentItemTextInput {
        ...ContentItemTextInput
      }
      ... on ContentItemPersonalProductSelectPaymentButton {
        ...ContentItemPersonalProductSelectPaymentButton
      }
      ... on ContentItemConfirm {
        ...ContentItemConfirm
      }
      ... on ContentItemPad {
        ...ContentItemPad
      }
      ... on ContentItemMarkdown {
        ...ContentItemMarkdown
      }
      ... on ContentItemRadio {
        ...ContentItemRadio
      }
      ... on ContentItemChoice {
        ...ContentItemChoice
      }
      ... on ContentItemLottie {
        ...ContentItemLottie
      }
      ... on ContentItemText {
        ...ContentItemText
      }
      ... on ContentItemButton {
        ...ContentItemButton
      }
      ... on ContentItemList {
        ...ContentItemList
      }
      ... on ContentItemInfoCard {
        ...ContentItemInfoCard
      }
      ... on ContentItemInfoButton {
        ...ContentItemInfoButton
      }
      ... on ContentItemSelectedPackageCard {
        ...ContentItemSelectedPackageCard
      }
      ... on ContentItemSelectedPackageCards {
        ...ContentItemSelectedPackageCards
      }
      ... on ContentItemPackageCards {
        ...ContentItemPackageCards
      }
      ... on ContentItemPackageCardPower {
        ...ContentItemPackageCardPower
      }
      ... on ContentItemPersonalProductPreview {
        ...ContentItemPersonalProductPreview
      }
      ... on ContentItemImage {
        ...ContentItemImage
      }
      ... on ContentItemCoverPicker {
        ...ContentItemCoverPicker
      }
      ... on ContentItemScrollableItemsPicker {
        ...ContentItemScrollableItemsPicker
      }
      ... on ContentItemDatePicker {
        ...ContentItemDatePicker
      }
      ... on ContentItemMultiSelect {
        ...ContentItemMultiSelect
      }
      ... on ContentItemScrollPicker {
        ...ContentItemScrollPicker
      }
      ... on ContentItemPersonalProductReviewItem {
        ...ContentItemPersonalProductReviewItem
      }
      ... on ContentItemRowIconTextBanner {
        ...ContentItemRowIconTextBanner
      }
      ... on ContentItemYuCoinPower {
        ...ContentItemYuCoinPower
      }
      ... on ContentItemYugiConfirm {
        ...ContentItemYugiConfirm
      }
      ... on ContentItemPersonalProductInfo {
        ...ContentItemPersonalProductInfo
      }
      ... on ContentItemGpDetails {
        ...ContentItemGpDetails
      }
      ... on ContentItemMultiButton {
        ...ContentItemMultiButton
      }
      ... on ContentItemSelectedPackageAccordion {
        ...ContentItemSelectedPackageAccordion
      }
      ... on ContentItemAgePercentCoverPicker {
        ...ContentItemAgePercentCoverPicker
      }
      ... on ContentItemCostPayoutBenefitCard {
        ...ContentItemCostPayoutBenefitCard
      }
      ... on ContentItemDropdownInput {
        ...ContentItemDropdownInput
      }
      ... on ContentItemHint {
        ...ContentItemHint
      }
    }
    footer {
      __typename
      ... on ContentItemButton {
        ...ContentItemButton
      }
      ... on ContentItemOverlay {
        ...ContentItemOverlay
      }
      ... on ContentItemMultiButton {
        ...ContentItemMultiButton
      }
      ... on ContentItemFade {
        ...ContentItemFade
      }
      ... on ContentItemPad {
        ...ContentItemPad
      }
      ... on ContentItemMarkdown {
        ...ContentItemMarkdown
      }
    }
    header {
      __typename
      ... on ContentItemHeaderBar {
        ...ContentItemHeaderBar
      }
      ... on ContentItemProgressBar {
        ...ContentItemProgressBar
      }
      ... on ContentItemProgressSteps {
        ...ContentItemProgressSteps
      }
      ... on ContentItemSearchPostcode {
        ...ContentItemSearchPostcode
      }
      ... on ContentItemMarkdown {
        ...ContentItemMarkdown
      }
      ... on ContentItemProcessingTimer {
        ...ContentItemProcessingTimer
      }
    }
    absolute {
      id
      shouldAccountForHeader
      item {
        __typename
        ... on ContentItemImage {
          ...ContentItemImage
        }
        ... on ContentItemCollapsingHeaderProductInfo {
          ...ContentItemCollapsingHeaderProductInfo
        }
        ... on ContentItemFullScreenSwiper {
          ...ContentItemFullScreenSwiper
        }
        ... on ContentItemFullScreenLottieSwiper {
          ...ContentItemFullScreenLottieSwiper
        }
        ... on ContentItemCollapsingHeaderAgePercentProductInfo {
          ...ContentItemCollapsingHeaderAgePercentProductInfo
        }
      }
    }
  }
}
