query GetPersonalProductStepDetached($productId: String!, $stepId: String!) {
  getPersonalProductStepDetached(productId: $productId, stepId: $stepId) {
    stepId
    customerProductId
    stepData
    body {
      __typename
      ... on ContentItemPersonalProductFaqs {
        ...ContentItemPersonalProductFaqs
      }
      ... on ContentItemPersonalProductDocuments {
        ...ContentItemPersonalProductDocuments
      }
      ... on ContentItemText {
        ...ContentItemText
      }
      ... on ContentItemTextInput {
        ...ContentItemTextInput
      }
      ... on ContentItemCoverPicker {
        ...ContentItemCoverPicker
      }
      ... on ContentItemSelectedPackageCard {
        ...ContentItemSelectedPackageCard
      }
      ... on ContentItemSelectedPackageCards {
        ...ContentItemSelectedPackageCards
      }
      ... on ContentItemSelectedPackageAccordion {
        ...ContentItemSelectedPackageAccordion
      }
      ... on ContentItemButton {
        ...ContentItemButton
      }
      ... on ContentItemPad {
        ...ContentItemPad
      }
      ... on ContentItemMarkdown {
        ...ContentItemMarkdown
      }
      ... on ContentItemRowIconTextBanner {
        ...ContentItemRowIconTextBanner
      }
      ... on ContentItemDropdownInput {
        ...ContentItemDropdownInput
      }
      ... on ContentItemHint {
        ...ContentItemHint
      }
    }
  }
}
