export enum HealthProviderCapability {
  STEP_COUNT = "STEP_COUNT",
  MINDFUL_MINUTES = "MINDFUL_MINUTES",
  CYCLING_DISTANCE = "CYCLING_DISTANCE",
  HEART_RATE = "HEART_RATE",
  WORKOUT_MINUTES = "WORKOUT_MINUTES",
  ACTIVITIES = "ACTIVITIES",
  CALORIES = "CALORIES",
  WHEELCHAIR_PUSHES = "WHEELCHAIR_PUSHES",
}
